import type { Config } from "@react-router/dev/config";

export default {
	ssr: false,
	prerender: [
		"/",
		"/how-it-works",
		"/about",
		"/suppliers",
		"/privacy",
		"/terms",
		"/guides",
		"/guides/sink-cut-outs-drainer-grooves",
		"/guides/kitchen-island-worktop-overhangs",
		"/guides/check-my-worktop-quote",
		"/guides/quartz-vs-porcelain-worktops",
		"/guides/20mm-vs-30mm-quartz-worktops",
		"/guides/stone-splashback-vs-tiles",
		"/guides/how-to-compare-worktop-quotes",
		"/guides/kitchen-company-vs-direct-worktops",
		"/guides/how-much-do-quartz-worktops-cost",
		"/guides/wren-worktop-quote-comparison",
		"/guides/howdens-worktop-quote-comparison",
		"/guides/magnet-worktop-quote-comparison",
		"/guides/best-worktop-for-busy-kitchen",
		"/guides/are-quartz-worktops-worth-it",
		"/guides/ogee-vs-bullnose-worktop-edge",
		"/guides/quartz-vs-granite-worktops",
		"/guides/porcelain-worktops-pros-cons",
		"/guides/kitchen-worktop-templating",
		"/guides/worktop-upstands-vs-splashbacks",
		"/guides/waterfall-ends-mitred-build-ups",
		"/guides/worktop-joins-slab-layout",
		"/guides/worktop-edge-profiles",

	],
} satisfies Config;
