import { useMemo, useState } from "react";

type MatchData = { postcode:string; projectType:string; material:string; style:string; budget:string; timescale:string; measurements:string; existingQuote:string; name:string; email:string; phone:string; bestTime:string; notes:string; };
const initialData:MatchData={postcode:"",projectType:"Kitchen worktops",material:"Not sure yet",style:"",budget:"",timescale:"",measurements:"",existingQuote:"",name:"",email:"",phone:"",bestTime:"",notes:""};
const steps=["Project","Stone","Budget","Quote","Contact"];
const LEAD_API="https://stonematch.patrick-deakin.workers.dev/api/lead";

export function MatchWizard(){
 const [step,setStep]=useState(0); const [data,setData]=useState<MatchData>(initialData); const [submitted,setSubmitted]=useState(false); const [submitting,setSubmitting]=useState(false); const [consent,setConsent]=useState(false); const [error,setError]=useState("");
 const progress=useMemo(()=>((step+1)/steps.length)*100,[step]); const update=(field:keyof MatchData,value:string)=>setData(c=>({...c,[field]:value}));
 function next(){ if(step===0&&!data.postcode.trim()){setError("Please add the project postcode so we know where to match.");return;} setError("");setStep(c=>Math.min(c+1,steps.length-1));window.requestAnimationFrame(()=>document.getElementById("match-wizard")?.scrollIntoView({behavior:"smooth",block:"start"})); }
 function back(){setError("");setStep(c=>Math.max(c-1,0));}
 async function submit(){
  if(submitting)return;
  if(!data.name.trim()||!data.email.trim()||!data.phone.trim()){setError("Please add your name, email and phone number so we can discuss your quote or project.");return;}
  if(!consent){setError("Please confirm that StoneMatch may use these details to deal with your enquiry.");return;}
  setError("");setSubmitting(true);
  try{
   const response=await fetch(LEAD_API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});
   const result=await response.json().catch(()=>({}));
   if(!response.ok||!result.ok)throw new Error(result.error||"Submission failed");
   setSubmitted(true);
  }catch(e){console.error(e);setError("We couldn't send your project just now. Please try again, or email enquiries@stonematch.co.uk.");}
  finally{setSubmitting(false);}
 }
 if(submitted)return <div className="wizard-success"><span className="eyebrow dark">Quote check received</span><h3>Thanks, {data.name}.</h3><p>Your details are safely with StoneMatch. We'll review what you've sent and get in touch to understand the brief before recommending any next step.</p><button className="text-link" onClick={()=>{setSubmitted(false);setStep(0);setData(initialData);setConsent(false)}}>Start another enquiry →</button></div>;
 return <div id="match-wizard" className="wizard"><div className="wizard-top"><div><span>Step {step+1} of {steps.length}</span><strong>{steps[step]}</strong></div><div className="wizard-progress"><i style={{width:`${progress}%`}}/></div></div>
 {step===0&&<section className="wizard-step"><p className="eyebrow dark">Let's start with the basics</p><h3>Where is the project, and what are you working on?</h3><p className="wizard-copy">Whether you already have a quote or are starting from scratch, this helps us keep the advice relevant to your project.</p><div className="form-row"><label>Project postcode<input value={data.postcode} onChange={e=>update("postcode",e.target.value)} placeholder="e.g. B68 8AB"/></label><label>Project type<select value={data.projectType} onChange={e=>update("projectType",e.target.value)}><option>Kitchen worktops</option><option>Utility room</option><option>Bathroom / vanity</option><option>Outdoor kitchen</option><option>Commercial project</option><option>Other</option></select></label></div></section>}
 {step===1&&<section className="wizard-step"><p className="eyebrow dark">Now the stone</p><h3>Do you already know what you want?</h3><p className="wizard-copy">If you know the material or colour, tell us. If not, choose “Not sure yet” and we'll work from the look and budget you have in mind.</p><label>Preferred material<select value={data.material} onChange={e=>update("material",e.target.value)}><option>Not sure yet</option><option>Quartz</option><option>Porcelain</option><option>Granite</option><option>Marble</option><option>Natural stone</option></select></label><label>Colour, style or inspiration<textarea rows={4} value={data.style} onChange={e=>update("style",e.target.value)} placeholder="For example: warm white with gold veining, Taj Mahal look, dark dramatic stone..."/></label></section>}
 {step===2&&<section className="wizard-step"><p className="eyebrow dark">Let's make the comparison useful</p><h3>What budget and timescale are you working to?</h3><p className="wizard-copy">This stops us suggesting options that don't fit the real brief.</p><div className="form-row"><label>Approximate budget<select value={data.budget} onChange={e=>update("budget",e.target.value)}><option value="">Choose a range</option><option>Under £1,500</option><option>£1,500 – £2,500</option><option>£2,500 – £4,000</option><option>£4,000 – £6,000</option><option>£6,000+</option><option>Not sure</option></select></label><label>When do you need it?<select value={data.timescale} onChange={e=>update("timescale",e.target.value)}><option value="">Choose timescale</option><option>ASAP</option><option>Within 2 weeks</option><option>Within 1 month</option><option>1–3 months</option><option>3+ months</option><option>Just researching</option></select></label></div></section>}
 {step===3&&<section className="wizard-step"><p className="eyebrow dark">The StoneMatch quote check</p><h3>Already got a worktop quote?</h3><p className="wizard-copy">Tell us who quoted, the material/specification and approximate price. If you don't have one yet, simply leave this blank and tell us what plans or sizes you have.</p><label>Existing quote details<textarea rows={4} value={data.existingQuote} onChange={e=>update("existingQuote",e.target.value)} placeholder="For example: £4,850 from kitchen retailer, 20mm Calacatta-style quartz, templating and fitting included..."/></label><label>Measurements or plan details<textarea rows={3} value={data.measurements} onChange={e=>update("measurements",e.target.value)} placeholder="Approximate dimensions, number of runs/islands, or tell us what plans you have available."/></label><label>Anything else we should know?<textarea rows={3} value={data.notes} onChange={e=>update("notes",e.target.value)} placeholder="Special edges, waterfall ends, splashbacks, preferred brands or anything you're unsure about..."/></label></section>}
 {step===4&&<section className="wizard-step"><p className="eyebrow dark">Last step</p><h3>Where should we send our thoughts?</h3><p className="wizard-copy">A quick conversation can help us compare the specification properly rather than judging a quote on price alone.</p><div className="form-row"><label>Your name<input value={data.name} onChange={e=>update("name",e.target.value)} placeholder="First and last name"/></label><label>Email<input type="email" value={data.email} onChange={e=>update("email",e.target.value)} placeholder="you@email.com"/></label></div><div className="form-row"><label>Phone<input type="tel" value={data.phone} onChange={e=>update("phone",e.target.value)} placeholder="Best contact number"/></label><label>Good time to call<input value={data.bestTime} onChange={e=>update("bestTime",e.target.value)} placeholder="e.g. Tomorrow after 4pm"/></label></div><div className="review-box"><strong>Your StoneMatch brief</strong><span>{data.postcode} · {data.projectType}</span><span>{data.material} · {data.budget||"Budget to discuss"} · {data.timescale||"Timescale to discuss"}</span></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree that StoneMatch can use my details to respond to this enquiry and, where needed, share relevant project information with suitable suppliers to obtain options. See the <a href="/privacy">Privacy Notice</a>.</span></label></section>}
 {error&&<p className="wizard-error">{error}</p>}<div className="wizard-actions">{step>0?<button type="button" className="wizard-back" onClick={back}>← Back</button>:<span/>}{step<steps.length-1?<button type="button" className="button gold" onClick={next}>Continue →</button>:<button type="button" className="button gold" onClick={submit} disabled={submitting}>{submitting?"Sending…":"Send for my free check →"}</button>}</div><p className="wizard-note">Free for homeowners. No obligation. We compare the brief, not just the headline price.</p></div>;
}
