import { useState } from "react";
declare global { interface Window { fbq?: (...args: unknown[]) => void; } }
const API="https://stonematch.patrick-deakin.workers.dev/api/lead";
export function QuickQuoteCheck(){
 const [files,setFiles]=useState<File[]>([]); const [have,setHave]=useState("Existing worktop quote"); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState(""); const [postcode,setPostcode]=useState(""); const [details,setDetails]=useState(""); const [consent,setConsent]=useState(false); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
 async function submit(){if(!name||!email||!phone){setError("Please add your name, email and phone number.");return}if(!consent){setError("Please confirm we may use your details to respond.");return}setBusy(true);setError("");
 const payload={postcode,projectType:"Kitchen worktops",material:"Not sure yet",style:"",budget:"",timescale:"",measurements:have==="Kitchen plans / measurements"?details:"",existingQuote:have==="Existing worktop quote"?details:"",name,email,phone,bestTime:"",notes:`Paid social savings enquiry. Customer has: ${have}. ${have==="Just an idea / inspiration"?details:""}`};
 try{const body=new FormData();body.append("data",JSON.stringify(payload));files.forEach(file=>body.append("files",file));const r=await fetch(API,{method:"POST",body});const j=await r.json().catch(()=>({}));if(!r.ok||!j.ok)throw new Error();window.fbq?.("track","Lead",{content_name:"StoneMatch paid social savings enquiry",content_category:have});setDone(true)}catch{setError("We couldn't send this just now. Please try again.")}finally{setBusy(false)}}
 if(done)return <div className="wizard-success"><p className="eyebrow dark">Received</p><h3>Thanks, {name}.</h3><p>StoneMatch has your details. We'll review what you have and look for the strongest-value suitable route before getting in touch.</p></div>;
 return <div className="wizard"><section className="wizard-step"><p className="eyebrow dark">Quick StoneMatch Savings Check</p><h3>What do you have?</h3><label>I'm starting with<select value={have} onChange={e=>setHave(e.target.value)}><option>Existing worktop quote</option><option>Kitchen plans / measurements</option><option>Just an idea / inspiration</option></select></label><label>{have==="Existing worktop quote"?"Quote details":have==="Kitchen plans / measurements"?"Plan / measurement details":"Tell us what you're looking for"}<textarea rows={4} value={details} onChange={e=>setDetails(e.target.value)} placeholder={have==="Existing worktop quote"?"Price, material, supplier and specification — whatever you have to hand.":"A few details are enough to get started."}/></label><label className="upload-field"><span>Upload your quote, kitchen plan or photos <small>(optional)</small></span><input type="file" multiple accept=".pdf,.jpg,.jpeg,.png,.webp,application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{const next=Array.from(e.target.files||[]).slice(0,5);if(next.some(f=>f.size>10*1024*1024)){setError("Each upload must be under 10MB.");e.target.value="";setFiles([]);return}setError("");setFiles(next)}}/><small>PDF, JPG, PNG or WEBP · up to 5 files · 10MB each</small>{files.length>0&&<strong>{files.length} {files.length===1?"file":"files"} ready to upload</strong>}</label><div className="form-row"><label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Phone<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)}/></label></div><div className="form-row"><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Project postcode <small>(optional)</small><input value={postcode} onChange={e=>setPostcode(e.target.value)}/></label></div><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I agree StoneMatch can use my details to respond to this enquiry. See the <a href="/privacy">Privacy Notice</a>.</span></label>{error&&<p className="wizard-error">{error}</p>}<button className="button gold" type="button" onClick={submit} disabled={busy}>{busy?"Sending…":"£ See how much I can save →"}</button><p className="wizard-note">Free for homeowners. No obligation. We'll look for a better-value route — and if your current deal is already strong, we'll tell you.</p></section></div>
}