import { useEffect, useState, type ReactNode } from "react";
export function Brand(){return <a className="brand" href="/" aria-label="StoneMatch home"><span className="brand-mark" aria-hidden="true"><span>SM</span></span><span className="brand-copy"><span><strong>STONE</strong>MATCH</span><small className="brand-tagline">SMARTER STONE. BETTER VALUE.</small></span></a>}
export function PrimaryTabs(){return <nav className="primary-tabs" aria-label="Main navigation"><a href="/guides/check-my-worktop-quote">Save on Worktops</a><a href="/materials">Explore Materials</a><a href="/worktop-matcher">Worktop Matcher</a><a href="/why-stonematch">Why StoneMatch?</a><a href="/about">About Us</a></nav>}
export function Header(){return <header className="site-header"><nav className="nav shell"><Brand/><div className="nav-links"><a className="shortlist-nav" href="/shortlist">Shortlist</a><a className="start-match" href="/guides/check-my-worktop-quote#check-my-quote">£ See how much I can save</a></div></nav><div className="shell"><PrimaryTabs/></div></header>}
export function Footer(){return <footer><div className="shell footer-inner"><Brand/><div className="footer-copy"><p>The stone you want. The right supplier. <strong>Better value.</strong></p><div className="footer-links"><a href="mailto:enquiries@stonematch.co.uk">enquiries@stonematch.co.uk</a><a href="https://www.instagram.com/stonematchuk/" target="_blank" rel="noreferrer">Instagram</a><a href="/guides/check-my-worktop-quote">Save on Worktops</a><a href="/materials">Explore Materials</a><a href="/materials/quartz">Quartz</a><a href="/materials/porcelain">Porcelain</a><a href="/materials/marble">Marble</a><a href="/materials/granite">Granite</a><a href="/worktop-matcher">Worktop Matcher</a><a href="/why-stonematch">Why StoneMatch?</a><a href="/about">About Us</a><a href="/shortlist">Shortlist</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></div><p className="legal-note">StoneMatch is a trading name of Deakin Surfaces Limited. Registered in England and Wales. Company number 17413451.</p></div><span>© 2026 StoneMatch</span></div></footer>}
function SavingsStory(){
 const [show,setShow]=useState(false);
 useEffect(()=>{const dismissed=sessionStorage.getItem("stonematch-project-001-dismissed");if(dismissed)return;let scrollShown=false;const reveal=()=>{if(!scrollShown&&window.scrollY>window.innerHeight*.35){scrollShown=true;setShow(true)}};const timer=window.setTimeout(()=>setShow(true),10000);window.addEventListener("scroll",reveal,{passive:true});return()=>{window.clearTimeout(timer);window.removeEventListener("scroll",reveal)}},[]);
 const close=()=>{sessionStorage.setItem("stonematch-project-001-dismissed","1");setShow(false)};
 if(!show)return null;
 return <aside className="savings-story" aria-label="Real StoneMatch saving"><button className="savings-story-close" onClick={close} aria-label="Close savings story">×</button><p className="savings-story-kicker">REAL STONEMATCH SAVING · PROJECT 001</p><strong className="savings-story-amount">£1,400 <em>SAVED</em></strong><p className="savings-story-copy">Our first customer came to StoneMatch with a <b>£3,600</b> worktop quote. We found a <b>£2,200</b> option — including a full splashback.</p><div className="savings-story-stats"><span>Nearly 39% less</span><span>Deposit paid ✓</span><span>Installation booked for November ✓</span></div><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">£ See how much I can save →</a><small>Project in progress. We’ll update this story after installation.</small></aside>
}
export function Page({children}:{children:ReactNode}){return <><Header/><main>{children}</main><SavingsStory/><Footer/></>}