import { GuideMetadata } from "../components/guide-metadata";
import { GuideNavigation } from "../components/guide-navigation";
import { Page } from "../components/site-shell";
export function meta(){return [{tagName:"link",rel:"canonical",href:"https://stonematch.co.uk/guides/20mm-vs-30mm-quartz-worktops/"},{title:"20mm vs 30mm Quartz Worktops: Which Should You Choose? | StoneMatch"},{name:"description",content:"20mm vs 30mm quartz worktops explained. Compare appearance, edge profiles, cost and kitchen style, with independent StoneMatch guidance."}]}
export default function ThicknessGuide(){return <Page><GuideMetadata title={"20mm vs 30mm Quartz Worktops: Which Should You Choose?"} canonical={"https://stonematch.co.uk/guides/20mm-vs-30mm-quartz-worktops/"}/>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Guide</p><h1>20mm vs 30mm Quartz.<br/><em>Which should you choose?</em></h1><p className="lead">Ten millimetres sounds small, but it can noticeably change the proportions of your kitchen. Neither thickness is automatically better — the right choice depends on cabinetry, edge detail, design and budget.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Compare my worktop options →</a></div></section>
<section className="section light"><div className="shell"><p className="eyebrow dark">At a glance</p><h2>Think design first.<br/><em>Not simply thicker = better.</em></h2><div className="material-choices"><div className="material-choice dark"><small>20mm Quartz</small><strong>Slim & contemporary</strong><span>A cleaner, lighter visual line that works especially well with modern and handleless cabinetry.</span></div><div className="material-choice"><small>30mm Quartz</small><strong>More substantial</strong><span>A thicker visible edge that can add visual weight to Shaker kitchens, larger islands and more traditional designs.</span></div><div className="material-choice"><small>Edge detail</small><strong>Part of the decision</strong><span>Your chosen thickness affects the proportions of bullnose, Ogee and other feature profiles. Decide thickness and edge together.</span></div><div className="material-choice"><small>Budget</small><strong>Compare the whole job</strong><span>Material thickness can affect price, but slab yield, cut-outs, edges, splashbacks and installation can matter just as much.</span></div></div></div></section>
<section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">StoneMatch view</p><h2>Spend extra where<br/><em>you can actually see it.</em></h2></div><div className="reason-copy dark-copy"><p>For a sleek modern kitchen, 20mm can look more deliberate than 30mm. For a substantial island or traditional kitchen, 30mm may suit the proportions better.</p><p><strong>The better question isn't “Which is best?” It's “Which looks right in my kitchen, and is the extra spend worth it?”</strong></p><a className="text-link" href="/guides/worktop-edge-profiles">Compare worktop edge profiles →</a></div></div></section>
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Before you order</p><h2>Compare the complete<br/><em>specification.</em></h2></div><div className="reason-copy"><p>Check material, thickness, edge profile, upstands, splashbacks, cut-outs, templating and installation before comparing two prices. A cheaper headline quote isn't necessarily the better-value installed job.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Send StoneMatch my quote →</a></div></div></section>
<GuideNavigation/></Page>}