import { Page } from "../components/site-shell";
export function meta(){return [{title:"About StoneMatch | A Smarter Way to Buy Stone Worktops"},{name:"description",content:"Why StoneMatch exists: independent stone industry knowledge helping homeowners compare worktop materials, specifications, fabricators and prices with confidence."}]}
export default function About(){return <Page>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">About StoneMatch</p><h1>Stone industry knowledge.<br/><em>On your side.</em></h1><p className="lead">StoneMatch was created to help homeowners buy beautiful stone worktops without paying more than they need to.</p></div></section>

<section className="section light"><div className="shell split"><div><p className="eyebrow dark">Why we exist</p><h2>A beautiful worktop shouldn't require you to become a <em>stone expert.</em></h2></div><div className="reason-copy dark-copy"><p>Quotes that look similar can cover different materials, specifications, fabrication and installation standards.</p><p>StoneMatch brings industry knowledge into your buying decision. We help homeowners understand what they're being offered, compare suitable options and connect with reputable fabricators.</p><p><strong>The aim is simple: use our industry knowledge to find a strong installed option and help you keep more of your budget.</strong></p></div></div></section>

<section className="section dark-section"><div className="shell"><p className="eyebrow">What we check</p><h2>Four parts of the deal.</h2><div className="steps"><article className="step dark-card"><span>01</span><h3>Stone</h3><p>Is the material right for the look, use and budget?</p></article><article className="step dark-card"><span>02</span><h3>Specification</h3><p>Thickness, edges, cut-outs, upstands and the details that affect the finished job.</p></article><article className="step dark-card"><span>03</span><h3>Fabricator</h3><p>Who is templating, manufacturing and installing your worktops?</p></article><article className="step dark-card"><span>04</span><h3>Price</h3><p>Does the complete proposition represent good value like-for-like?</p></article></div></div></section>

<section className="section light"><div className="shell split"><div><p className="eyebrow dark">Independent by design</p><h2>If your current quote is right,<br/><em>we'll say so.</em></h2></div><div className="reason-copy dark-copy"><p>StoneMatch isn't about changing your supplier for the sake of it. If what you already have represents the right combination of product, service and price, that's useful to know.</p><p>If there's a stronger option, we'll explain what is different so you can decide for yourself.</p><a className="button gold" href="/#enquire">See if I can save →</a></div></div></section>
</Page>}
