import { Page } from "../components/site-shell";
import { edgeGuidance } from "../data/partner-range";

export function meta(){return [{title:"Worktop Edge Details & Fabrication | StoneMatch"},{name:"description",content:"StoneMatch guidance on double bevel, bullnose, shark nose, double pencil, ogee and built-up porcelain worktop edges."}]}

const cards=[
 {title:"20mm worktops",intro:"A slimmer, contemporary worktop gives you more freedom to use the edge profile as part of the design.",items:["Bullnose — premium, softer profile","Shark Nose — premium and especially effective with handleless kitchens","Double Bevel — clean, understated finish","Double Pencil — a great alternative to Bullnose without the same fabrication cost"]},
 {title:"30mm stone",intro:"With a 30mm worktop, the material already has a substantial appearance. We normally let that thickness do the talking.",items:["Double Bevel — our standard recommendation for 30mm Quartz, Granite and Marble","Ogee — a more decorative option for traditional or luxury kitchens"]},
 {title:"Porcelain",intro:"Porcelain behaves differently to quartz and natural stone, so we recommend edge details that suit the material rather than simply copying a stone profile.",items:["Double Bevel — our standard porcelain edge","12mm built-up / mitred edge — premium option when a more substantial look is wanted","Built-ups work particularly well on statement islands, waterfall ends and bespoke tables"]}
];

export default function EdgeDetails(){return <Page>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Edge Adviser</p><h1>The finishing detail that <em>changes the whole look.</em></h1><p className="lead">The best edge isn't simply the most expensive one. It should suit the material, thickness, cabinetry and the look you're trying to achieve.</p></div></section>
<section className="section light"><div className="shell"><p className="eyebrow dark">Our recommendations</p><h2>Start with the <em>worktop.</em></h2><div className="edge-card-grid">{cards.map(card=><article className="edge-card" key={card.title}><h3>{card.title}</h3><p>{card.intro}</p><ul>{card.items.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Premium fabrication</p><h2>Want the look of a thick slab <em>without the weight?</em></h2></div><div className="reason-copy"><p><strong>Built-up porcelain</strong> uses carefully mitred pieces to create the appearance of a much thicker worktop. Where technically suitable, we recommend starting with 12mm porcelain to keep weight sensible while creating a substantial architectural finish.</p><p>It's a premium fabrication method, but on statement islands, waterfall ends and bespoke furniture it can completely transform the design.</p></div></div></section>
<section className="section cream-band"><div className="shell"><p className="eyebrow dark">StoneMatch principle</p><h2>Let the material <em>speak for itself.</em></h2><div className="edge-principles">{edgeGuidance.map(edge=><article key={edge.id}><h3>{edge.name}{edge.premium?" · Premium":""}</h3><p>{edge.recommendation}</p><small>{edge.suitableMaterials.join(" · ")} · {edge.recommendedThickness}</small></article>)}</div><div className="edge-cta"><p>Not sure which edge suits your kitchen? Send us your plans or kitchen design and we'll recommend the finish we'd use.</p><a className="button gold" href="/#enquire">Ask StoneMatch →</a></div></div></section>
</Page>}
