import { Page } from "../components/site-shell";

const suppliers=[
 ["The Marble & Granite Centre","https://www.themarbleandgranitecentre.co.uk/"],
 ["Brachot","https://www.brachot.com/"],
 ["Imperial Stone Group","https://www.imperialstonegroup.com/"],
 ["Gerald Culliford","https://geraldculliford.co.uk/"],
 ["Develli","https://develli.co.uk/"]
];

const seoSchema={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","name":"Granite Worktops","url":"https://stonematch.co.uk/materials/granite","description":"Natural Granite kitchen worktops, slab selection, finishes and buying guidance from StoneMatch.","publisher":{"@id":"https://stonematch.co.uk/#organization"}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://stonematch.co.uk/"},{"@type":"ListItem","position":2,"name":"Materials","item":"https://stonematch.co.uk/materials"},{"@type":"ListItem","position":3,"name":"Granite Worktops","item":"https://stonematch.co.uk/materials/granite"}]}]};
export function meta(){return [
 {title:"Granite Worktops | Natural Stone | StoneMatch"},
 {name:"description",content:"Explore granite worktops, natural slabs and finishes, then let StoneMatch look for a better-value fabrication and installation route."}
]}

export default function Granite(){return <Page><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(seoSchema)}}/>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch · Natural Stone</p><h1>Granite worktops.<br/><em>Natural and hard-wearing.</em></h1><p className="lead">Granite combines the individuality of natural stone with excellent everyday durability. StoneMatch helps you choose the exact slab and compare the complete templated, fabricated and installed proposition.</p><div className="colour-actions"><a className="button gold" href="/?material=Granite#enquire">Find my Granite for less →</a><a className="text-link light-link" href="/materials">Compare materials →</a></div></div></section>
<section className="section light"><div className="shell split"><div><p className="eyebrow dark">Why Granite</p><h2>Built by nature.<br/><em>Made for real kitchens.</em></h2></div><div className="reason-copy dark-copy"><p>Granite is valued for strength, heat resistance and distinctive natural pattern. Depending on the stone, the look can range from quiet and consistent to dramatic movement, crystals and bold mineral detail.</p><p>Because every block is natural, samples and photographs are only a guide. StoneMatch recommends viewing the actual slab for highly figured colours and confirming the fabrication specification before ordering.</p></div></div></section>
<section className="section cream-band"><div className="shell"><p className="eyebrow dark">Specification</p><h2>What to <em>consider.</em></h2><div className="material-choices"><div className="material-choice dark"><small>Selection</small><strong>Natural slab</strong><span>Colour, movement and mineral structure vary naturally. Select the exact slab when variation matters to the design.</span></div><div className="material-choice"><small>Performance</small><strong>Hard-wearing</strong><span>Granite is a strong practical worktop material, but care requirements still vary with the particular stone and finish.</span></div><div className="material-choice"><small>Finish</small><strong>Multiple options</strong><span>Polished is common, with honed, leathered or textured finishes available on selected granites.</span></div><div className="material-choice"><small>Fabrication</small><strong>Plan the details</strong><span>Cut-outs, joints, edge profiles, overhangs and slab yield all contribute to the finished appearance and price.</span></div></div></div></section>
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Choose your slab</p><h2>Find the stone.<br/><em>Then StoneMatch it.</em></h2></div><div className="reason-copy"><p>Visit a specialist supplier and note the slab or block reference for the granite you prefer. StoneMatch can then help coordinate the material with an appropriate fabricator and compare the complete installed quotation.</p><p><strong>We compare the finished worktop proposition — not simply a square-metre slab price.</strong></p></div></div><div className="shell supplier-links">{suppliers.map(([name,url])=><a href={url} target="_blank" rel="noreferrer" key={name}>{name}<span>↗</span></a>)}</div></section>
<section className="section light"><div className="shell split"><div><p className="eyebrow dark">StoneMatch it</p><h2>Already found<br/><em>your Granite?</em></h2></div><div className="reason-copy dark-copy"><p>Send us the slab details, kitchen plan or existing quotation. We will compare suitable fabrication routes and the complete installed price to help you get the Granite you want for better value.</p><a className="button gold" href="/?material=Granite#enquire">Find my Granite saving →</a></div></div></section><section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">StoneMatch guides</p><h2>Understand the material.<br/><em>Then compare the job.</em></h2></div><div className="reason-copy dark-copy"><p><a className="text-link" href="/guides/how-to-compare-worktop-quotes">How to compare worktop quotes →</a></p><p><a className="text-link" href="/guides/worktop-edge-profiles">Worktop edge profiles →</a></p><p><a className="text-link" href="/worktop-matcher">Use the Worktop Matcher →</a></p></div></div></section>
</Page>}
