import { Page } from "../components/site-shell";
export function meta(){return [{title:"Kitchen Worktop Guides | Quartz, Porcelain, Prices & Quotes | StoneMatch"},{name:"description",content:"Independent StoneMatch guides to choosing, pricing and comparing Quartz, Porcelain, Granite and Marble worktops. Understand specifications before you buy."}]}
const groups=[
{title:"Choose your material",intro:"Start with the surface that suits the way your kitchen needs to look and perform.",links:[["Quartz vs Porcelain","/guides/quartz-vs-porcelain-worktops","Compare two of the most popular engineered worktop choices."],["Explore worktop materials","/materials","Quartz, Porcelain, Marble and Granite in one place."],["Worktop Matcher","/worktop-matcher","Not sure? Narrow the choice around your project."]]},
{title:"Understand the specification",intro:"Small specification choices can make a large difference to both appearance and fabrication cost.",links:[["20mm vs 30mm Quartz","/guides/20mm-vs-30mm-quartz-worktops","How thickness changes the look and the buying decision."],["Worktop edge profiles","/guides/worktop-edge-profiles","Double bevel, Bullnose, Ogee and built-up details explained."],["Stone splashback vs tiles","/guides/stone-splashback-vs-tiles","Compare design impact, joints, cleaning and slab use."]]},
{title:"Understand the price",intro:"Compare the complete installed job rather than relying on a headline rate.",links:[["How much do Quartz worktops cost?","/guides/how-much-do-quartz-worktops-cost","The factors that actually move an installed Quartz quotation."],["Quartz worktop prices","/guides/quartz-worktop-prices","Material, slab yield, fabrication, template and installation."],["How to compare worktop quotes","/guides/how-to-compare-worktop-quotes","Our like-for-like checklist before you pay a deposit."]]},
{title:"Already have a kitchen quote?",intro:"Keep the kitchen you want and independently check the worktop element before committing.",links:[["Kitchen company vs specialist route","/guides/kitchen-company-vs-direct-worktops","Understand the different routes from slab to finished kitchen."],["Wren worktop quote guide","/guides/wren-worktop-quote-comparison","What to compare if you already have a Wren quotation."],["Howdens worktop quote guide","/guides/howdens-worktop-quote-comparison","Check the complete specification before committing."],["Magnet worktop quote guide","/guides/magnet-worktop-quote-comparison","Compare stone, fabrication, fitting and final price."]]}
];
const schema={"@context":"https://schema.org","@type":"CollectionPage","name":"StoneMatch Kitchen Worktop Guides","url":"https://stonematch.co.uk/guides","description":"Independent guides to choosing, specifying, pricing and comparing stone kitchen worktops.","publisher":{"@id":"https://stonematch.co.uk/#organization"}};
export default function Guides(){return <Page><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Guides</p><h1>Know what you're buying.<br/><em>Before you buy it.</em></h1><p className="lead">Independent guidance to help you choose the material, understand the specification and compare the complete installed price of your new worktops.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Already quoted? StoneMatch it →</a></div></section>
{groups.map((g,i)=><section className={i%2===0?"section light":"section cream-band"} key={g.title}><div className="shell"><p className="eyebrow dark">StoneMatch buying advice</p><h2>{g.title}</h2><p className="section-intro">{g.intro}</p><div className="material-choices">{g.links.map(([t,u,d],j)=><a className={j===0?"material-choice dark":"material-choice"} href={u} key={u}><strong>{t}</strong><span>{d}</span><small>Read guide →</small></a>)}</div></div></section>)}
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Ready to compare?</p><h2>Before you buy it.<br/><em>StoneMatch it.</em></h2></div><div className="reason-copy"><p>Upload your kitchen plan and existing worktop quotation. Tell us your preferred material if you know it. We'll compare the specification and see whether there's a suitable better-value route.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Upload my plan & quote →</a></div></div></section>
</Page>}