import { GuideMetadata } from "../components/guide-metadata";
import { GuideNavigation } from "../components/guide-navigation";
import { Page } from "../components/site-shell";
const faq=[{"@type":"Question","name":"What should I compare in a kitchen worktop quote?","acceptedAnswer":{"@type":"Answer","text":"Compare the exact material, thickness, edge details, cut-outs, upstands and splashbacks, templating, installation, joins, slab layout, guarantee and aftercare before comparing the final installed price."}},{"@type":"Question","name":"Is the cheapest worktop quote always the best value?","acceptedAnswer":{"@type":"Answer","text":"No. A lower headline price can exclude fabrication details, splashbacks, templating or installation. Compare the complete installed specification first."}},{"@type":"Question","name":"Can StoneMatch check an existing worktop quote?","acceptedAnswer":{"@type":"Answer","text":"Yes. Homeowners can send StoneMatch an existing quotation and kitchen plan for an independent comparison of the specification and potential better-value routes."}}];
const schema={"@context":"https://schema.org","@type":"FAQPage","mainEntity":faq};
export function meta(){return [{tagName:"link",rel:"canonical",href:"https://stonematch.co.uk/guides/how-to-compare-worktop-quotes/"},{title:"How to Compare Kitchen Worktop Quotes Properly | StoneMatch"},{name:"description",content:"Learn how to compare quartz, porcelain, granite and marble worktop quotes like-for-like: material, thickness, edges, cut-outs, splashbacks, templating, installation and guarantees."}]}
const checks=[["Material","Brand, colour, finish and slab specification should be clear. Similar-looking materials are not automatically equivalent."],["Thickness","Check whether the quote is based on 20mm, 30mm or another construction."],["Edges","Standard and feature edge profiles can carry very different fabrication requirements."],["Cut-outs","Sink, hob, tap holes, drainer grooves and recessed details should be identified."],["Upstands & splashbacks","Compare heights, quantities and whether full-height pieces are included."],["Template & installation","Confirm measuring, delivery and fitting are included and understand who is responsible."],["Joins & slab layout","The cheapest nesting is not always the best-looking layout. Pattern flow and join positions matter."],["Guarantee & aftercare","Know what material cover and installation support you are actually receiving."]];
export default function CompareQuotes(){return <Page><GuideMetadata title={"How to Compare Kitchen Worktop Quotes Properly"} canonical={"https://stonematch.co.uk/guides/how-to-compare-worktop-quotes/"}/>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Buying Guide</p><h1>How to compare worktop quotes.<br/><em>Like-for-like.</em></h1><p className="lead">Two quotes can both say “quartz worktops” and still describe very different jobs. Before choosing the lowest number, make sure you're comparing the same material, fabrication and installation.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Send us your quote →</a></div></section>
<section className="section light"><div className="shell"><p className="eyebrow dark">The StoneMatch checklist</p><h2>Eight things to check<br/><em>before paying a deposit.</em></h2><div className="edge-principles">{checks.map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">The trap</p><h2>Don't compare<br/><em>headline prices.</em></h2></div><div className="reason-copy"><p>A lower quotation can stop being cheaper once missing splashbacks, premium edges, extra cut-outs, templating or installation are added back in.</p><p><strong>Compare the complete installed specification first. Then compare the price.</strong></p></div></div></section>
<section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Already been quoted?</p><h2>Before you buy it.<br/><em>StoneMatch it.</em></h2></div><div className="reason-copy dark-copy"><p>Send us your existing quotation and kitchen plan. We'll look at the specification and see whether there is a better-value route worth considering. If your current deal is already strong, we'll tell you that too.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Check my worktop quote →</a></div></div></section>
<section className="section light"><div className="shell split"><div><p className="eyebrow dark">Keep researching</p><h2>Make the next comparison<br/><em>with the full picture.</em></h2></div><div className="reason-copy dark-copy"><p><a className="text-link" href="/guides/kitchen-company-vs-direct-worktops">Kitchen company vs specialist route →</a></p><p><a className="text-link" href="/guides/how-much-do-quartz-worktops-cost">What affects Quartz worktop cost? →</a></p><p><a className="text-link" href="/guides/worktop-edge-profiles">Compare worktop edge profiles →</a></p><p><a className="text-link" href="/worktops-west-midlands">Stone worktops in the West Midlands →</a></p></div></div></section>
<GuideNavigation/></Page>}