import { Page } from "../components/site-shell";

export function meta(){return [{tagName:"link",rel:"canonical",href:"https://stonematch.co.uk/how-it-works/"},{title:"Compare Worktop Quotes: How StoneMatch Works"},{name:"description",content:"Upload your kitchen plan or worktop quote. See how StoneMatch compares Quartz, Porcelain, Marble and Granite specifications and suitable installed options."}]}

const steps=[
["01","Tell us what matters","Start with whatever you have — measurements, a kitchen plan, inspiration photos, a stone name, an existing quote or simply a budget. The better we understand the outcome you want, the better we can match it."],
["02","We find suitable routes","We look at your location, design, material preferences, timescale and budget to identify suitable stone choices and fabricators capable of delivering the project."],
["03","We look for the saving","Instead of you repeating the same conversation with multiple companies, StoneMatch can approach suitable suppliers and compare the overall proposition — not just the headline number."],
["04","You decide","We bring the strongest-value suitable option back to you and show you what it means for your project. You stay in control and choose whether you want to proceed. No pressure and no obligation."],
];

export default function HowItWorks(){return <Page><section className="page-hero"><div className="shell narrow"><p className="eyebrow">How StoneMatch works</p><h1>The worktops you want.<br/><em>For less.</em></h1><p className="lead">Tell us what you want and StoneMatch does the shopping around for you — looking for a better-value route without cutting corners on the finished job.</p><a className="button gold" href="/guides/check-my-worktop-quote/#check-my-quote">See how much I could save →</a></div></section><section className="section light"><div className="shell"><div className="long-steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></article>)}</div></div></section><section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">What we compare</p><h2>Saving money matters.<br/><em>So does getting it right.</em></h2></div><div className="reason-copy dark-copy"><p>A worktop quote is only good value if the material, fabrication, templating, installation and aftercare are right for the project.</p><p>Our aim is to reduce what you pay without losing sight of the stone, fabrication, templating, installation and aftercare that make the finished job work.</p><a className="text-link" href="/guides/check-my-worktop-quote/#check-my-quote">Find my better-value option →</a></div></div></section><section className="section light"><div className="shell narrow"><p className="eyebrow dark">Before you send your project</p><h2>What do you need to provide?</h2><p>A kitchen plan or measurements, your preferred material and any existing worktop quote give us a useful starting point. Include your project postcode, intended timescale and a good time to call. If you have not chosen a colour, tell us the look you want.</p><h2>Do you need an existing quotation?</h2><p>No. You can start with a plan or an idea. If you already have a quote, send the full specification so we can compare the material, thickness, edges, cut-outs, splashbacks, template and installation.</p><h2>Is a saving guaranteed?</h2><p>The result depends on your project and the quotation being compared. We look for a suitable better-value option, and we will tell you if your current deal is already strong. Compare the complete finished job before deciding.</p><h2>What happens before the stone is made?</h2><p>The appointed fabricator confirms the final material, dimensions and fabrication details through its templating and approval process. Check the written specification and payment terms before committing.</p><p><a className="text-link" href="/guides/how-to-compare-worktop-quotes/">Use the complete worktop quote checklist →</a></p><p><a className="text-link" href="/guides/kitchen-worktop-templating/">Prepare for worktop templating →</a></p><a className="button gold" href="/guides/check-my-worktop-quote/#check-my-quote">Upload my plan & quote →</a></div></section></Page>}
