import { Page } from "../components/site-shell";

export function meta(){return [{title:"How StoneMatch Works | StoneMatch"},{name:"description",content:"See how StoneMatch helps homeowners save money on stone worktops by comparing suitable materials, suppliers, fabricators and installed prices."}]}

const steps=[
["01","Tell us what matters","Start with whatever you have — measurements, a kitchen plan, inspiration photos, a stone name, an existing quote or simply a budget. The better we understand the outcome you want, the better we can match it."],
["02","We find suitable routes","We look at your location, design, material preferences, timescale and budget to identify suitable stone choices and fabricators capable of delivering the project."],
["03","We look for the saving","Instead of you repeating the same conversation with multiple companies, StoneMatch can approach suitable suppliers and compare the overall proposition — not just the headline number."],
["04","You decide","We bring the strongest-value suitable option back to you and show you what it means for your project. You stay in control and choose whether you want to proceed. No pressure and no obligation."],
];

export default function HowItWorks(){return <Page><section className="page-hero"><div className="shell narrow"><p className="eyebrow">How StoneMatch works</p><h1>The worktops you want.<br/><em>For less.</em></h1><p className="lead">Tell us what you want and StoneMatch does the shopping around for you — looking for a better-value route without cutting corners on the finished job.</p><a className="button gold" href="/#enquire">See how much I could save →</a></div></section><section className="section light"><div className="shell"><div className="long-steps">{steps.map(([n,t,d])=><article key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></article>)}</div></div></section><section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">What we compare</p><h2>Saving money matters.<br/><em>So does getting it right.</em></h2></div><div className="reason-copy dark-copy"><p>A worktop quote is only good value if the material, fabrication, templating, installation and aftercare are right for the project.</p><p>Our aim is to reduce what you pay without losing sight of the stone, fabrication, templating, installation and aftercare that make the finished job work.</p><a className="text-link" href="/#enquire">Find my better-value option →</a></div></div></section></Page>}
