import { GuideNavigation } from "../components/guide-navigation";
import { Page } from "../components/site-shell";
const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://stonematch.co.uk/"},{"@type":"ListItem","position":2,"name":"Guides","item":"https://stonematch.co.uk/guides/"},{"@type":"ListItem","position":3,"name":"Kitchen Company Worktops vs Buying Direct","item":"https://stonematch.co.uk/guides/kitchen-company-vs-direct-worktops/"}]};
export function meta(){return [{tagName:"link",rel:"canonical",href:"https://stonematch.co.uk/guides/kitchen-company-vs-direct-worktops/"},{title:"Kitchen Company Worktops vs Buying Direct | StoneMatch"},{name:"description",content:"Compare buying quartz, porcelain, granite or marble worktops through a kitchen retailer with specialist fabrication routes. Learn what to compare before you buy."}]}
export default function DirectGuide(){return <Page><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Buying Guide</p><h1>Kitchen company worktops vs buying direct.<br/><em>What's the difference?</em></h1><p className="lead">The stone may look similar, but the route from slab to finished kitchen can be very different. The smartest comparison is not retailer versus fabricator — it's the complete installed specification versus the complete installed price.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Compare my existing quote →</a></div></section>
<section className="section light"><div className="shell"><p className="eyebrow dark">What you're paying for</p><h2>Follow the route<br/><em>from quote to installation.</em></h2><div className="material-choices"><div className="material-choice dark"><small>Kitchen retailer</small><strong>One buying journey</strong><span>Convenient when purchasing the complete kitchen, but the worktop price may include additional retail margin or an outsourced fabrication route.</span></div><div className="material-choice"><small>Specialist route</small><strong>Closer to fabrication</strong><span>A specialist worktop route can give more visibility over material, slab choice, fabrication details and the company templating and installing the job.</span></div><div className="material-choice"><small>Specification</small><strong>Compare like-for-like</strong><span>Check thickness, edges, upstands, splashbacks, cut-outs, template, installation and guarantee before deciding which quote offers better value.</span></div><div className="material-choice"><small>StoneMatch</small><strong>Independent comparison</strong><span>We help homeowners compare suitable routes rather than assuming one buying method is always cheaper or better.</span></div></div></div></section>
<section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">The key question</p><h2>Who is actually making<br/><em>and fitting your worktops?</em></h2></div><div className="reason-copy dark-copy"><p>Ask who templates the kitchen, who fabricates the slabs and who installs the finished pieces. Then compare material specification, workmanship, turnaround, aftercare and price.</p><p><strong>Buying closer to the fabricator can offer excellent value, but the quality of the fabricator matters more than the label on the sales route.</strong></p><a className="text-link" href="/guides/how-to-compare-worktop-quotes">Use our quote comparison checklist →</a></div></div></section>
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Already have a retailer quote?</p><h2>Before you buy it.<br/><em>StoneMatch it.</em></h2></div><div className="reason-copy"><p>Send us the quotation and your kitchen plan. We'll compare the specification and see whether another suitable installed route offers better value. If your existing deal is already strong, we'll tell you.</p><a className="button gold" href="/guides/check-my-worktop-quote#check-my-quote">Check my worktop quote →</a></div></div></section>
<GuideNavigation/></Page>}