import { Page } from "../components/site-shell";
import { quartzBrands } from "../data/quartz-brands";
import { porcelainBrands } from "../data/porcelain-brands";
const naturalSuppliers=[["The Marble & Granite Centre","https://www.themarbleandgranitecentre.co.uk/"],["Brachot","https://www.brachot.com/"],["Imperial Stone Group","https://www.imperialstonegroup.com/"],["Gerald Culliford","https://geraldculliford.co.uk/"],["Develli","https://develli.co.uk/"]];
export function meta(){return [{title:"Explore Worktop Materials | StoneMatch"},{name:"description",content:"Explore Quartz, Porcelain, Marble and Granite worktops with StoneMatch. Compare curated ranges, leading brands and natural stone."}]}
export default function Materials(){return <Page>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">Explore Materials</p><h1>Four materials.<br/><em>One easier decision.</em></h1><p className="lead">Start with the surface that interests you, compare the options and shortlist what you like. Not sure where to begin? Our Worktop Matcher will narrow it down for you.</p><a className="button gold" href="/worktop-matcher">Use the Worktop Matcher →</a></div></section>
<section className="section light"><div className="shell"><p className="eyebrow dark">Choose your surface</p><h2>What are you <em>looking for?</em></h2><div className="material-choices"><a className="material-choice dark" href="/materials/quartz"><small>Engineered stone</small><strong>Quartz</strong><span>Huge design choice, straightforward care and options across a wide range of budgets.</span></a><a className="material-choice" href="/materials/porcelain"><small>High performance</small><strong>Porcelain</strong><span>Heat resistant, design-led and ideal for slim profiles or technically suitable built-up edges.</span></a><a className="material-choice" href="/materials/marble"><small>Natural stone</small><strong>Marble</strong><span>Individual slabs with unique veining and character. Best selected from the exact slab.</span></a><a className="material-choice" href="/materials/granite"><small>Natural stone</small><strong>Granite</strong><span>Hard-wearing natural stone with every slab bringing its own colour, pattern and movement.</span></a></div></div></section>
<section className="section cream-band"><div className="shell"><p className="eyebrow dark">Quartz catalogue</p><h2>Explore <em>Quartz.</em></h2><p className="section-intro">Compare the StoneMatch Partner Range with established quartz brands.</p><div className="brand-grid">{quartzBrands.map((b,i)=><a className={i===0?"brand-tile featured":"brand-tile"} href={i===0?"/materials/quartz/partner-range":`/materials/quartz/brands/${b.slug}`} key={b.slug}><small>{i===0?"STONEMATCH CURATED":"QUARTZ"}</small><strong>{b.name}</strong><span>{i===0?"Contract · Contract Plus · Vital · Essence":"Explore brand →"}</span></a>)}</div></div></section>
<section className="section light"><div className="shell"><p className="eyebrow dark">Porcelain catalogue</p><h2>Explore <em>Porcelain.</em></h2><p className="section-intro">Compare our Partner Range with leading porcelain and ultra-compact surface brands.</p><div className="brand-grid">{porcelainBrands.map((b,i)=><a className={i===0?"brand-tile featured":"brand-tile"} href={i===0?"/materials/porcelain/partner-range":`/materials/porcelain/brands/${b.slug}`} key={b.slug}><small>{i===0?"STONEMATCH CURATED":"PORCELAIN"}</small><strong>{b.name}</strong><span>{i===0?"Curated by StoneMatch":"Explore brand →"}</span></a>)}</div></div></section>
<section id="natural-stone" className="section dark-section"><div className="shell split"><div><p className="eyebrow">Marble & Granite</p><h2>Choose the exact slab.<br/><em>We handle the rest.</em></h2><div className="colour-actions"><a className="button gold" href="/materials/marble">Explore Marble →</a><a className="text-link light-link" href="/materials/granite">Explore Granite →</a></div></div><div className="reason-copy"><p>Natural stone varies from slab to slab. StoneMatch recommends viewing and reserving the exact piece you want rather than choosing from a small sample.</p><p>Photograph the slab and its block or reference number and send it to us. We'll help coordinate the material and fabrication around your project.</p></div></div><div className="shell supplier-links">{naturalSuppliers.map(([n,u])=><a href={u} target="_blank" rel="noreferrer" key={n}>{n}<span>↗</span></a>)}</div></section>
</Page>}
