import { useEffect, useState } from "react";
import { Page } from "../components/site-shell";
import { partnerQuartz } from "../data/partner-range";
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
type ColourImages={slab?:string;installations:string[]};
const colourImages:Record<string,ColourImages>={
"Bianco Galaxy":{slab:"/quartz/partner-range/bianco-galaxy-details-2.jpg",installations:["/quartz/partner-range/bianco-galaxy-2.jpg"]},
"White Dove":{installations:["/quartz/partner-range/white-dove-installed-1.jpg","/quartz/partner-range/white-dove-installed-2.jpg","/quartz/partner-range/white-dove-installed-3.jpg","/quartz/partner-range/white-dove-installed-4.jpg","/quartz/partner-range/white-dove-installed-5.jpg","/quartz/partner-range/white-dove-installed-6.jpg","/quartz/partner-range/white-dove-ingram-1.webp","/quartz/partner-range/white-dove-ingram-2.webp","/quartz/partner-range/white-dove-ingram-3.webp","/quartz/partner-range/white-dove-ingram-4.webp","/quartz/partner-range/white-dove-ingram-5.webp","/quartz/partner-range/white-dove-ingram-6.webp","/quartz/partner-range/white-dove-ingram-7.webp","/quartz/partner-range/white-dove-ingram-8.webp"]},
"Bianco Shimmer":{slab:"/quartz/partner-range/bianco-shimmer-2.jpg",installations:["/quartz/partner-range/bianco-shimmer-2-2.jpg"]},
"Super White":{slab:"/quartz/partner-range/super-white-1.jpg",installations:["/quartz/partner-range/super-white-2.jpg","/quartz/partner-range/super-white-3.jpg"]},
"Snow White":{slab:"/quartz/partner-range/snow-white-details.jpg",installations:["/quartz/partner-range/snow-white-2.jpg","/quartz/partner-range/snow-white-fitted-2.jpg"]},
"Calacatta Gold":{installations:["/quartz/partner-range/calacatta-gold-installed-5.webp","/quartz/partner-range/calacatta-gold-installed-6.webp","/quartz/partner-range/calacatta-gold-installed-7.webp","/quartz/partner-range/calacatta-gold-installed-1.webp","/quartz/partner-range/calacatta-gold-installed-2.webp","/quartz/partner-range/calacatta-gold-installed-3.webp","/quartz/partner-range/calacatta-gold-installed-4.webp"]},
"Lydia Gold":{installations:["/quartz/partner-range/lydia-gold-installed.webp"]},
"London Grey":{installations:["/quartz/partner-range/london-grey-installed.webp"]},
"Arctic White":{installations:["/quartz/partner-range/arctic-white.jpg"]},
"Arabescato Verde":{installations:["/quartz/partner-range/arabescato-verde-installed-4.webp","/quartz/partner-range/arabescato-verde-installed-5.webp","/quartz/partner-range/arabescato-verde-installed-6.webp"]},
"Misterio Oro":{slab:"/quartz/partner-range/misterio-oro-2.jpg",installations:["/quartz/partner-range/misterio-oro-fitted.jpg"]}
}
export function meta({params}:any){const colour=partnerQuartz.find(c=>slugify(c.name)===params.slug);return [{title:`${colour?.name||"Partner Range Quartz"} Quartz Worktop | StoneMatch`},{name:"description",content:colour?`Explore ${colour.name}, a ${colour.tier} quartz in the StoneMatch Partner Range. See design guidance, specifications and find a better-value installed route.`:"Explore StoneMatch Partner Range quartz."}]}
export default function PartnerColour({params}:any){
 const colour=partnerQuartz.find(c=>slugify(c.name)===params.slug);const [saved,setSaved]=useState(false);const [lightboxIndex,setLightboxIndex]=useState<number|null>(null);
 useEffect(()=>{if(!colour)return;try{const list=JSON.parse(localStorage.getItem("stonematch-shortlist")||"[]");setSaved(list.includes(colour.name));}catch{setSaved(false)}},[colour?.name]);
 useEffect(()=>{if(lightboxIndex===null)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setLightboxIndex(null);if(e.key==="ArrowRight")setLightboxIndex(i=>i===null?null:(i+1)%images.installations.length);if(e.key==="ArrowLeft")setLightboxIndex(i=>i===null?null:(i-1+images.installations.length)%images.installations.length)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[lightboxIndex]);
 if(!colour)return <Page><section className="page-hero"><div className="shell narrow"><p className="eyebrow">Partner Range Quartz</p><h1>Colour not found.</h1><a className="button gold" href="/materials/quartz/partner-range">Back to Partner Range →</a></div></section></Page>;
 const toggle=()=>{let list:string[]=[];try{list=JSON.parse(localStorage.getItem("stonematch-shortlist")||"[]")}catch{}const next=list.includes(colour.name)?list.filter(x=>x!==colour.name):[...list,colour.name];localStorage.setItem("stonematch-shortlist",JSON.stringify(next));setSaved(next.includes(colour.name));window.dispatchEvent(new Event("stonematch-shortlist"));};
 const quoteHref=`/?material=Quartz&colour=${encodeURIComponent(colour.name)}&source=partner-range#enquire`;const related=partnerQuartz.filter(c=>c.tier===colour.tier&&c.name!==colour.name).slice(0,3);const images=colourImages[colour.name]||{installations:[]};const heroImage=images.slab||images.installations[0];
 return <Page>
  <section className={`page-hero colour-hero stone-${colour.visual}`}><div className="shell narrow"><p className="eyebrow">Partner Range · {colour.tier}</p><h1>{colour.name}</h1><p className="lead">{colour.description||"A curated StoneMatch quartz selected for its combination of design, practicality and installed value."}</p><div className="colour-actions"><a className="button gold" href={quoteHref}>£ See how much I can save →</a><button className="shortlist-button" onClick={toggle}>{saved?"♥ Saved to shortlist":"♡ Add to my shortlist"}</button></div>{saved&&<a className="text-link shortlist-view-link light-link" href="/shortlist">View my shortlist →</a>}</div></section>
  <section className="section light"><div className="shell colour-layout"><div className="colour-visual">{heroImage?<figure className="brand-feature-image"><img src={heroImage} alt={`${colour.name} quartz ${images.slab?"slab":"installed worktop"}`}/><figcaption>{colour.name} · {images.slab?"approved slab photography":"verified installed project photography"}</figcaption></figure>:<div className={`stone-preview stone-${colour.visual}`}><i/><span>{colour.name}</span></div>}<p className="image-note">{heroImage?`${images.slab?"Approved slab":"Verified installed project"} · ${colour.name}. Quartz pattern can vary by production batch, so confirm the current physical sample or slab before ordering.`:`Colour guide · ${colour.name}. An approved slab image is still being sourced. No generic or unverified image has been substituted.`}</p>{images.installations.length>0&&<div className="installation-gallery"><h3>See it installed</h3><div className="related-colours">{images.installations.map((src,index)=><button type="button" className="gallery-thumb" key={src} onClick={()=>setLightboxIndex(index)} aria-label={`Open ${colour.name} installation image ${index+1}`}><figure className="related-project-image"><img src={src} alt={`${colour.name} installed quartz worktop ${index+1}`}/></figure></button>)}</div></div>}</div><div className="colour-spec"><p className="eyebrow dark">StoneMatch recommendation</p><h2>Know what you’re <em>choosing.</em></h2><p>{colour.description||"A versatile surface chosen to work beautifully across a wide range of kitchen styles."}</p><dl><div><dt>Collection</dt><dd>{colour.tier}</dd></div><div><dt>Material</dt><dd>Quartz</dd></div>{colour.underlying&&<div><dt>Range reference</dt><dd>{colour.underlying}</dd></div>}{colour.supplier&&<div><dt>Supplier reference</dt><dd>{colour.supplier}</dd></div>}{colour.finish&&<div><dt>Finish</dt><dd>{colour.finish}</dd></div>}{colour.thicknesses&&<div><dt>Thickness</dt><dd>{colour.thicknesses.join(" · ")}</dd></div>}</dl><div className="spec-tags">{colour.tags.slice(0,4).map(tag=><span key={tag}>{tag.replaceAll("-"," ")}</span>)}</div><p className="spec-note">Final slab availability, production batch, finish and thickness are confirmed as part of your StoneMatch quotation. Where a thickness or finish is not shown here, StoneMatch will verify it before you commit.</p></div></div></section>
  {lightboxIndex!==null&&images.installations[lightboxIndex]&&<div className="image-lightbox" role="dialog" aria-modal="true" aria-label={`${colour.name} installation gallery`} onClick={()=>setLightboxIndex(null)}><button type="button" className="lightbox-close" onClick={()=>setLightboxIndex(null)} aria-label="Close gallery">×</button>{images.installations.length>1&&<button type="button" className="lightbox-prev" onClick={e=>{e.stopPropagation();setLightboxIndex((lightboxIndex-1+images.installations.length)%images.installations.length)}} aria-label="Previous image">‹</button>}<img src={images.installations[lightboxIndex]} alt={`${colour.name} installed quartz worktop ${lightboxIndex+1}`} onClick={e=>e.stopPropagation()}/>{images.installations.length>1&&<button type="button" className="lightbox-next" onClick={e=>{e.stopPropagation();setLightboxIndex((lightboxIndex+1)%images.installations.length)}} aria-label="Next image">›</button>}<div className="lightbox-count">{lightboxIndex+1} / {images.installations.length}</div></div>}
  <section className="section cream-band"><div className="shell"><div className="catalogue-head"><div><p className="eyebrow dark">Compare your shortlist</p><h2>Also in <em>{colour.tier}.</em></h2></div><a className="text-link" href="/materials/quartz/partner-range">View all Partner Range colours →</a></div><div className="related-colours">{related.map(c=>{const image=(colourImages[c.name]?.slab||colourImages[c.name]?.installations[0]);return <a href={`/materials/quartz/partner-range/${slugify(c.name)}`} key={c.name}>{image?<div className="related-project-image"><img src={image} alt={`${c.name} installed quartz worktop`}/></div>:<div className={`mini-stone stone-${c.visual}`}><i/></div>}<strong>{c.name}</strong><span>{c.tags.slice(0,2).map(t=>t.replaceAll("-"," ")).join(" · ")}</span></a>})}</div></div></section>
  <section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Ready to save?</p><h2>Love it. <em>Let us find the value.</em></h2></div><div className="reason-copy"><p>Your favourite colour is only one part of the decision. StoneMatch brings the material, fabrication and installation together so you can compare the complete installed option.</p><div className="colour-actions"><button className="button gold" onClick={toggle}>{saved?"Remove from shortlist":"Add to shortlist →"}</button><a className="text-link light-link" href={quoteHref}>£ See how much I can save →</a></div></div></div></section>
 </Page>;
}
