import { Page } from "../components/site-shell";
import { partnerQuartz,type PartnerTier } from "../data/partner-range";
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
type CatalogueImage={src:string;kind:"project"|"slab";source:string};
const slab=(src:string,source="Quartz supplier")=>({src,kind:"slab" as const,source});
const project=(src:string)=>({src,kind:"project" as const,source:"StoneMatch project photography"});
const catalogueImages:Record<string,CatalogueImage>={
"Bianco Galaxy":slab("https://purplegranite.co.uk/cdn/shop/files/Bianco_Galaxy_Quartz.jpg?v=1781870071&width=1200","Purple Granite"),
"White Dove":project("/quartz/partner-range/white-dove-hero.webp"),
"White Shimmer":slab("https://purplegranite.co.uk/cdn/shop/files/Bianco-_1.jpg?v=1700150880&width=1200","Purple Granite · Bianco Shimmer"),
"Super White":slab("https://purplegranite.co.uk/cdn/shop/files/A203SuperWhiteSlab.jpg?v=1738229746&width=1200","Purple Granite"),
"Snow White":slab("https://purplegranite.co.uk/cdn/shop/files/A202SnowWhiteSlab.jpg?v=1738229565&width=1200","Purple Granite"),
"Calacatta Gold":slab("https://purplegranite.co.uk/cdn/shop/files/PQS_Calacatta_Gold_Slab.jpg?v=1757595487&width=1200","Purple Granite"),
"Arctic White":project("/quartz/partner-range/arctic-white.jpg"),
"Lydia Gold":slab("https://expressionquartz.com/wp-content/uploads/2024/11/lydia-gold-expression-quartz-2-1-1024x485.jpeg","Expression Quartz"),
"Carrara":slab("https://expressionquartz.com/wp-content/uploads/2022/01/Expression-Quartz-Surfaces-CARRARA-WHITE-SLAB--1024x494.jpg","Expression Quartz · Carrara White"),
"Toran":slab("https://expressionquartz.com/wp-content/uploads/2022/01/expression-quartz-surfaces-Statuario-Toran-slab-1024x512.jpg","Expression Quartz · Statuario Toran"),
"Perla":slab("https://expressionquartz.com/wp-content/uploads/2022/01/expression-quartz-surfaces-PERLA-GREY-SLAB--1024x495.jpg","Expression Quartz · Perla Grey"),
"Cold Spring":slab("https://expressionquartz.com/wp-content/uploads/2022/11/Expression-Quartz-Cold-Spring-Slab-edit-1024x512.jpg","Expression Quartz"),
"Four Seasons":slab("https://purplegranite.co.uk/cdn/shop/files/thumbnail_CS137_Four_Seasons_Slab.jpg?v=1754566711&width=1200","Purple Granite"),
"Taj Mahal":slab("https://expressionquartz.com/wp-content/uploads/2025/11/Taj-Mahal-expression-quartz-surfaces-scaled-e1762360745673-1024x508.jpg","Expression Quartz"),
"Ivy":slab("https://expressionquartz.com/wp-content/uploads/2023/08/expression-quartz-surfaces-Belgravia-slab-1024x512.jpg","Expression Quartz · Belgravia"),
"Calacatta Portugal":slab("https://purplegranite.co.uk/cdn/shop/files/thumbnail_CS135CalacattaPortugalSlab.jpg?v=1754560023&width=1200","Purple Granite"),
"Sorento Gold":slab("https://expressionquartz.com/wp-content/uploads/2025/11/Sorrento-Gold-Fitted-expression-quartz-surfaces-2-1024x512.jpg","Expression Quartz · Sorrento Gold"),
"Perla Venata":slab("https://expressionquartz.com/wp-content/uploads/2025/11/perla-venata-expression-quartz-surfaces-1-1024x576.jpg","Expression Quartz"),
"Arabescato Verde":project("/quartz/partner-range/arabescato-verde-gallery.webp"),
"Arabescato Oro":slab("https://expressionquartz.com/wp-content/uploads/2025/06/expression-quartz-arabescato-oro-surface-4-1024x521.jpg","Expression Quartz"),
"Fog":slab("https://purplegranite.co.uk/cdn/shop/files/Cloudy-_1.jpg?v=1762246537&width=1200","Purple Granite · Cloudy Gris"),
"London Grey":slab("https://purplegranite.co.uk/cdn/shop/files/LondonGrey1-_1.jpg?v=1700150935&width=1200","Purple Granite"),
"Imperial Black":slab("https://expressionquartz.com/wp-content/uploads/2024/11/imperial-black-expression-quartz-2-1-1024x512.jpg","Expression Quartz"),
"Himalaya":slab("https://expressionquartz.com/wp-content/uploads/2023/08/expression-quartz-surfaces-Himalaya-sab-e1715614825570-1024x508.jpg","Expression Quartz"),
"Fantasy Verde":slab("https://purplegranite.co.uk/cdn/shop/files/Cosy_Fantasy_Verde_Quartz.png?v=1781869689&width=1200","Purple Granite"),
"Pisa":slab("https://expressionquartz.com/wp-content/uploads/2022/11/Expression-Quartz-Surfaces-Pisa-Slab-image-1024x512.jpg","Expression Quartz"),
"Royal Oro":slab("https://expressionquartz.com/wp-content/uploads/2024/05/Expression-Quartz-Royal-Oro-Slab-1024x532.jpeg","Expression Quartz"),
"Montebello":slab("https://expressionquartz.com/wp-content/uploads/2025/06/expression-quartz-montebello-surface-1_1-1024x512.jpg","Expression Quartz"),
"Belgravia":slab("https://expressionquartz.com/wp-content/uploads/2023/08/expression-quartz-surfaces-Belgravia-slab-1024x512.jpg","Expression Quartz"),
"Calacatta Vagli":slab("https://expressionquartz.com/wp-content/uploads/2025/11/Calacatta-Vagli-expression-quartz-surfaces-1-1024x517.jpg","Expression Quartz"),
"Desert Gold":slab("https://expressionquartz.com/wp-content/uploads/2025/11/Desert-Gold-expression-quartz-surfaces-2-1024x519.jpg","Expression Quartz"),
"Santorini":slab("https://expressionquartz.com/wp-content/uploads/2022/11/expression-quartz-surfaces-Santorini-Slab-scaled-e1715614886102-1024x510.jpg","Expression Quartz"),
"Sandstorm":slab("https://expressionquartz.com/wp-content/uploads/2024/11/Sand-Storm-expression-quartz-1-1024x563.jpg","Expression Quartz · Sand Storm")
};
const ranges:{name:PartnerTier;tag:string;copy:string;pos:string}[]=[{name:"Contract",tag:"Simple. Versatile. Exceptional value.",copy:"An accessible collection of soft, easy-to-use colours designed to work beautifully across a wide range of kitchens.",pos:"Everyday simplicity"},{name:"Contract Plus",tag:"Popular designs. Excellent value.",copy:"Fast-moving colours chosen for customers who want current, versatile designs with an excellent balance of style and value.",pos:"Popular favourites"},{name:"Vital",tag:"Beautiful marble-inspired surfaces.",copy:"Popular marble effects with more distinctive movement and veining — ideal when you want the worktop to become part of the design.",pos:"Marble inspired"},{name:"Essence",tag:"Statement surfaces for exceptional spaces.",copy:"Our high-end collection of premium marble effects and statement designs for kitchens where the surface deserves to take centre stage.",pos:"Premium collection"}];
export function meta(){return [{title:"Partner Range Quartz Colours | StoneMatch"},{name:"description",content:"Explore StoneMatch Partner Range quartz across Contract, Contract Plus, Vital and Essence. Compare real slab imagery and installed projects, shortlist favourites and request an installed quotation."}]}
export default function PartnerRange(){return <Page><section className="page-hero partner-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Partner Range · Quartz</p><h1>Four collections.<br/><em>One simpler choice.</em></h1><p className="lead">Start with the collection that suits your project, then compare the colours visually. Save favourites as you go and send StoneMatch the shortlist when you’re ready.</p><div className="hero-actions"><a className="button gold" href="#colours">Explore colours →</a><a className="text-link light-link" href="/shortlist">View my shortlist →</a></div></div></section><section className="section light" id="colours"><div className="shell"><div className="range-grid">{ranges.map(r=>{const colours=partnerQuartz.filter(c=>c.tier===r.name);return <article className="range-product-section" key={r.name}><div className="range-heading"><div><p className="eyebrow dark">{r.pos}</p><h2>{r.name}</h2></div><div><h3>{r.tag}</h3><p>{r.copy}</p><strong>{colours.length} curated colours</strong></div></div><div className="colour-card-grid">{colours.map(c=>{const image=catalogueImages[c.name];return <a className="colour-product-card" href={`/materials/quartz/partner-range/${slugify(c.name)}`} key={c.name}>{image?<div className="catalogue-project-image"><img src={image.src} alt={image.kind==="project"?`${c.name} quartz installed worktop project`:`${c.name} quartz slab and surface`} loading="lazy"/><small>{image.kind==="project"?"GENUINE INSTALLED PROJECT":`SLAB / PRODUCT IMAGE · ${image.source}`}</small></div>:<div className={`mini-stone product-stone stone-${c.visual}`}><i/><small>IMAGE BEING VERIFIED</small></div>}<div className="colour-card-copy"><span>{r.name}</span><strong>{c.name}</strong><p>{c.tags.slice(0,3).map(t=>t.replaceAll("-"," ")).join(" · ")}</p><b>Explore colour →</b></div></a>})}</div></article>})}</div><p className="image-note">Installed-project cards use verified project photography. Slab and product images are labelled separately with their source. Quartz pattern, tone and movement should always be confirmed from the current physical sample or slab before ordering.</p></div></section><section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Not sure where to start?</p><h2>Let us <em>match you.</em></h2></div><div className="reason-copy dark-copy"><p>Answer a few quick questions about how you cook, the look you love and what matters most. We’ll recommend the material route that best fits your needs, then you can shortlist the colours you actually want to see.</p><a className="button gold" href="/worktop-matcher">Start the Worktop Matcher →</a></div></div></section></Page>}
