import { useEffect, useState } from "react";
import { Page } from "../components/site-shell";
import { partnerQuartz } from "../data/partner-range";
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const verifiedProjectImages:Record<string,string>={"White Dove":"/quartz/partner-range/white-dove.jpg","Arctic White":"/quartz/partner-range/arctic-white.jpg"};
export function meta({params}:any){const colour=partnerQuartz.find(c=>slugify(c.name)===params.slug);return [{title:`${colour?.name||"Partner Range Quartz"} Quartz Worktop | StoneMatch`},{name:"description",content:colour?`Explore ${colour.name}, a ${colour.tier} quartz in the StoneMatch Partner Range. See design guidance, specifications and request an installed quotation.`:"Explore StoneMatch Partner Range quartz."}]}
export default function PartnerColour({params}:any){
 const colour=partnerQuartz.find(c=>slugify(c.name)===params.slug);const [saved,setSaved]=useState(false);
 useEffect(()=>{if(!colour)return;try{const list=JSON.parse(localStorage.getItem("stonematch-shortlist")||"[]");setSaved(list.includes(colour.name));}catch{setSaved(false)}},[colour?.name]);
 if(!colour)return <Page><section className="page-hero"><div className="shell narrow"><p className="eyebrow">Partner Range Quartz</p><h1>Colour not found.</h1><a className="button gold" href="/materials/quartz/partner-range">Back to Partner Range →</a></div></section></Page>;
 const toggle=()=>{let list:string[]=[];try{list=JSON.parse(localStorage.getItem("stonematch-shortlist")||"[]")}catch{}const next=list.includes(colour.name)?list.filter(x=>x!==colour.name):[...list,colour.name];localStorage.setItem("stonematch-shortlist",JSON.stringify(next));setSaved(next.includes(colour.name));window.dispatchEvent(new Event("stonematch-shortlist"));};
 const quoteHref=`/?material=Quartz&colour=${encodeURIComponent(colour.name)}&source=partner-range#enquire`;const related=partnerQuartz.filter(c=>c.tier===colour.tier&&c.name!==colour.name).slice(0,3);const projectImage=verifiedProjectImages[colour.name];
 return <Page>
  <section className={`page-hero colour-hero stone-${colour.visual}`}><div className="shell narrow"><p className="eyebrow">Partner Range · {colour.tier}</p><h1>{colour.name}</h1><p className="lead">{colour.description||"A curated StoneMatch quartz selected for its combination of design, practicality and installed value."}</p><div className="colour-actions"><a className="button gold" href={quoteHref}>Get a quote in this colour →</a><button className="shortlist-button" onClick={toggle}>{saved?"♥ Saved to shortlist":"♡ Add to my shortlist"}</button></div>{saved&&<a className="text-link shortlist-view-link light-link" href="/shortlist">View my shortlist →</a>}</div></section>
  <section className="section light"><div className="shell colour-layout"><div className="colour-visual">{projectImage?<><img src={projectImage} alt={`${colour.name} quartz worktop installed in a StoneMatch partner project`} style={{width:"100%",display:"block",borderRadius:"2px",aspectRatio:"4 / 3",objectFit:"cover"}}/><p className="image-note">Real installed project · {colour.name}. Quartz pattern can vary by production batch, so confirm the current physical sample or slab before ordering.</p></>:<><div className={`stone-preview stone-${colour.visual}`}><i/><span>{colour.name}</span></div><p className="image-note">Design preview only · quartz varies by production batch. Confirm the current physical sample or slab before ordering.</p></>}</div><div className="colour-spec"><p className="eyebrow dark">StoneMatch recommendation</p><h2>Know what you’re <em>choosing.</em></h2><p>{colour.description||"A versatile surface chosen to work beautifully across a wide range of kitchen styles."}</p><dl><div><dt>Collection</dt><dd>{colour.tier}</dd></div><div><dt>Material</dt><dd>Quartz</dd></div>{colour.underlying&&<div><dt>Range reference</dt><dd>{colour.underlying}</dd></div>}{colour.supplier&&<div><dt>Supplier reference</dt><dd>{colour.supplier}</dd></div>}{colour.finish&&<div><dt>Finish</dt><dd>{colour.finish}</dd></div>}{colour.thicknesses&&<div><dt>Thickness</dt><dd>{colour.thicknesses.join(" · ")}</dd></div>}</dl><div className="spec-tags">{colour.tags.slice(0,4).map(tag=><span key={tag}>{tag.replaceAll("-"," ")}</span>)}</div><p className="spec-note">Final slab availability, production batch, finish and thickness are confirmed as part of your StoneMatch quotation. Where a thickness or finish is not shown here, StoneMatch will verify it before you commit.</p></div></div></section>
  <section className="section cream-band"><div className="shell"><div className="catalogue-head"><div><p className="eyebrow dark">Compare your shortlist</p><h2>Also in <em>{colour.tier}.</em></h2></div><a className="text-link" href="/materials/quartz/partner-range">View all Partner Range colours →</a></div><div className="related-colours">{related.map(c=><a href={`/materials/quartz/partner-range/${slugify(c.name)}`} key={c.name}><div className={`mini-stone stone-${c.visual}`}><i/></div><strong>{c.name}</strong><span>{c.tags.slice(0,2).map(t=>t.replaceAll("-"," ")).join(" · ")}</span></a>)}</div></div></section>
  <section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Ready to compare?</p><h2>Save it. Quote it. <em>StoneMatch it.</em></h2></div><div className="reason-copy"><p>Your favourite colour is only one part of the decision. StoneMatch brings the material, fabrication and installation together so you can compare the complete installed option.</p><div className="colour-actions"><button className="button gold" onClick={toggle}>{saved?"Remove from shortlist":"Add to shortlist →"}</button><a className="text-link light-link" href={quoteHref}>Quote {colour.name} →</a></div></div></div></section>
 </Page>;
}
