import { Page } from "../components/site-shell";
import { partnerQuartz,type PartnerTier } from "../data/partner-range";
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const projectImages:Record<string,string>={"White Dove":"/quartz/partner-range/white-dove-hero.webp","Arctic White":"/quartz/partner-range/arctic-white.jpg","Arabescato Verde":"/quartz/partner-range/arabescato-verde-gallery.webp"};
const ranges:{name:PartnerTier;tag:string;copy:string;pos:string}[]=[{name:"Contract",tag:"Simple. Versatile. Exceptional value.",copy:"An accessible collection of soft, easy-to-use colours designed to work beautifully across a wide range of kitchens.",pos:"Everyday simplicity"},{name:"Contract Plus",tag:"Popular designs. Excellent value.",copy:"Fast-moving colours chosen for customers who want current, versatile designs with an excellent balance of style and value.",pos:"Popular favourites"},{name:"Vital",tag:"Beautiful marble-inspired surfaces.",copy:"Popular marble effects with more distinctive movement and veining — ideal when you want the worktop to become part of the design.",pos:"Marble inspired"},{name:"Essence",tag:"Statement surfaces for exceptional spaces.",copy:"Our high-end collection of premium marble effects and statement designs for kitchens where the surface deserves to take centre stage.",pos:"Premium collection"}];
export function meta(){return [{title:"Partner Range Quartz Colours | StoneMatch"},{name:"description",content:"Explore StoneMatch Partner Range quartz across Contract, Contract Plus, Vital and Essence. Compare colour styles, shortlist favourites and request an installed quotation."}]}
export default function PartnerRange(){return <Page><section className="page-hero partner-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Partner Range · Quartz</p><h1>Four collections.<br/><em>One simpler choice.</em></h1><p className="lead">Start with the collection that suits your project, then compare the colours visually. Save favourites as you go and send StoneMatch the shortlist when you’re ready.</p><div className="hero-actions"><a className="button gold" href="#colours">Explore colours →</a><a className="text-link light-link" href="/shortlist">View my shortlist →</a></div></div></section>
<section className="section light" id="colours"><div className="shell"><div className="range-grid">{ranges.map(r=>{const colours=partnerQuartz.filter(c=>c.tier===r.name);return <article className="range-product-section" key={r.name}><div className="range-heading"><div><p className="eyebrow dark">{r.pos}</p><h2>{r.name}</h2></div><div><h3>{r.tag}</h3><p>{r.copy}</p><strong>{colours.length} curated colours</strong></div></div><div className="colour-card-grid">{colours.map(c=>{const image=projectImages[c.name];return <a className="colour-product-card" href={`/materials/quartz/partner-range/${slugify(c.name)}`} key={c.name}>{image?<div className="catalogue-project-image"><img src={image} alt={`${c.name} quartz installed project`} loading="lazy"/><small>GENUINE INSTALLED PROJECT</small></div>:<div className={`mini-stone product-stone stone-${c.visual}`}><i/><small>COLOUR GUIDE</small></div>}<div className="colour-card-copy"><span>{r.name}</span><strong>{c.name}</strong><p>{c.tags.slice(0,3).map(t=>t.replaceAll("-"," ")).join(" · ")}</p><b>Explore colour →</b></div></a>})}</div></article>})}</div><p className="image-note">Cards marked genuine installed project use verified project photography. Other previews are colour guides only and are never presented as real installations. Quartz pattern, tone and movement should always be confirmed from the current physical sample or slab before ordering.</p></div></section>
<section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Not sure where to start?</p><h2>Let us <em>match you.</em></h2></div><div className="reason-copy dark-copy"><p>Answer a few quick questions about how you cook, the look you love and what matters most. We’ll recommend the material route that best fits your needs, then you can shortlist the colours you actually want to see.</p><a className="button gold" href="/worktop-matcher">Start the Worktop Matcher →</a></div></div></section></Page>}
