import { Page } from "../components/site-shell";
import { porcelainBrands } from "../data/porcelain-brands";
const verifiedCount=porcelainBrands.filter((brand)=>brand.verified).length;
const seoSchema={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","name":"Porcelain Worktops","url":"https://stonematch.co.uk/materials/porcelain/","description":"Porcelain kitchen worktops, brands, edge details, specifications and buying guidance from StoneMatch.","publisher":{"@id":"https://stonematch.co.uk/#organization"}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://stonematch.co.uk/"},{"@type":"ListItem","position":2,"name":"Materials","item":"https://stonematch.co.uk/materials/"},{"@type":"ListItem","position":3,"name":"Porcelain Worktops","item":"https://stonematch.co.uk/materials/porcelain/"}]}]};
export function meta(){return [{tagName:"link",rel:"canonical",href:"https://stonematch.co.uk/materials/porcelain/"},{title:"Porcelain Worktops & Brands | StoneMatch"},{name:"description",content:"Explore porcelain worktops from the StoneMatch Partner Range and leading brands, then compare suitable routes for better installed value."}]}
export default function Porcelain(){return <Page><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(seoSchema)}}/>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Porcelain Catalogue</p><h1>The porcelain you want.<br/><em>For better value.</em></h1><p className="lead">Compare our curated Partner Range with leading porcelain and ultra-compact surface brands. StoneMatch helps you choose the design, understand the fabrication and find a strong-value route for the complete installed job.</p><div className="colour-actions"><a className="button gold" href="/materials/porcelain/partner-range/">Explore Partner Range →</a><a className="text-link light-link" href="/#enquire">See if I can save →</a></div></div></section>
<section className="section light"><div className="shell"><div className="catalogue-head"><div><p className="eyebrow dark">Porcelain brands</p><h2>Choose by <em>design and application.</em></h2></div><p className="section-intro">Brand matters, but so do slab size, thickness, finish, edge detail and fabrication. We bring those decisions together before you commit.</p><p className="image-note">{verifiedCount} of {porcelainBrands.length} catalogue sections currently have verified catalogue-level specifications. Remaining sections stay under specification check until confirmed.</p></div><div className="brand-grid">{porcelainBrands.map((b,i)=><a className={i===0?"brand-tile featured":"brand-tile"} href={i===0?"/materials/porcelain/partner-range":`/materials/porcelain/brands/${b.slug}/`} key={b.slug}><small>{i===0?"STONEMATCH CURATED":"PORCELAIN"}</small><strong>{b.name}</strong><span>{b.strapline}</span></a>)}</div></div></section>
<section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Why porcelain?</p><h2>Thin profile.<br/><em>Serious performance.</em></h2></div><div className="reason-copy"><p>Porcelain is a strong option where heat resistance, durability and large-format design matter. It can be kept deliberately slim or fabricated into a more substantial built-up look where the material and design allow.</p><p>Our standard porcelain edge recommendation is a clean double bevel. For statement work, 12mm material can also be mitred and built up where technically suitable.</p><a className="button gold" href="/guides/worktop-edge-profiles/">Compare edge details →</a></div></div></section><section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">StoneMatch guides</p><h2>Understand the material.<br/><em>Then compare the job.</em></h2></div><div className="reason-copy dark-copy"><p><a className="text-link" href="/guides/quartz-vs-porcelain-worktops/">Quartz vs Porcelain →</a></p><p><a className="text-link" href="/guides/worktop-edge-profiles/">Worktop edge profiles →</a></p><p><a className="text-link" href="/guides/stone-splashback-vs-tiles/">Stone splashback vs tiles →</a></p></div></div></section>
<section className="section light"><div className="shell narrow"><h2>Porcelain cleaning and care</h2><p><a className="text-link" href="/guides/porcelain-worktop-care/">Read the StoneMatch guide →</a></p></div></section></Page>}
