import { Page } from "../components/site-shell";
import { getPorcelainBrand } from "../data/porcelain-brands";
export function meta({params}:any){const b=getPorcelainBrand(params.slug);return [{title:`${b?.name||"Porcelain"} Worktops | StoneMatch`},{name:"description",content:b?`Explore ${b.name} porcelain worktops with StoneMatch. Compare applications, specifications and the complete installed option.`:"Explore porcelain worktop brands with StoneMatch."}]}
export default function PorcelainBrand({params}:any){const b=getPorcelainBrand(params.slug);if(!b)return <Page><section className="page-hero"><div className="shell narrow"><p className="eyebrow">Porcelain catalogue</p><h1>Brand not found.</h1><a className="button gold" href="/materials/porcelain">Back to Porcelain →</a></div></section></Page>;
return <Page>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch · Porcelain</p><h1>{b.name}</h1><p className="lead">{b.strapline}</p><div className="colour-actions"><a className="button gold" href={`/?material=Porcelain&style=${encodeURIComponent(b.name)}#enquire`}>Get a {b.name} quote →</a><a className="text-link light-link" href="/materials/porcelain">Compare porcelain brands →</a></div></div></section>
<section className="section light"><div className="shell colour-layout"><div className="colour-visual"><div className="stone-preview stone-soft"><i/><span>{b.name}</span></div><p className="image-note">Design guide only · choose the exact colour from the current manufacturer collection and StoneMatch will confirm its live specification before ordering.</p></div><div className="colour-spec"><p className="eyebrow dark">Brand overview</p><h2>Where it <em>fits.</em></h2><p>{b.summary}</p><dl><div><dt>Formats</dt><dd>{b.formats}</dd></div><div><dt>Thickness</dt><dd>{b.thicknesses}</dd></div><div><dt>Finishes</dt><dd>{b.finishes}</dd></div></dl><div className="spec-tags">{b.bestFor.map(x=><span key={x}>{x}</span>)}</div><p className="spec-note">{b.note}</p>{b.website&&<a className="text-link" href={b.website} target="_blank" rel="noreferrer">View the manufacturer's current collection ↗</a>}</div></div></section>
<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">StoneMatch it</p><h2>Found a colour<br/><em>you love?</em></h2></div><div className="reason-copy"><p>Send us the brand and colour — or your existing kitchen worktop quotation. We can compare the material, specification, fabrication and installed price before you commit.</p><a className="button gold" href={`/?material=Porcelain&style=${encodeURIComponent(b.name)}#enquire`}>Start my match →</a></div></div></section>
</Page>}
