import { Page } from "../components/site-shell";
import { quartzBrands } from "../data/quartz-brands";

export function meta(){return [{title:"Quartz Worktops & Brands | StoneMatch"},{name:"description",content:"Compare StoneMatch Partner Range quartz with Silestone, Caesarstone, Technistone and other quartz brands. StoneMatch helps match the right surface, supplier and installed value."}]}

export default function QuartzCatalogue(){return <Page>
 <section className="page-hero quartz-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Quartz Catalogue</p><h1>Start with the look.<br/><em>Then compare properly.</em></h1><p className="lead">Quartz should not be a choice between hundreds of names on a screen. Start with our curated Partner Range or explore recognised brands, then let StoneMatch compare the surface, specification, fabrication and installed value.</p><div className="hero-actions"><a className="button gold" href="/materials/quartz/partner-range">Explore Partner Range →</a><a className="text-link light-link" href="/worktop-matcher">Not sure? Use the Worktop Matcher →</a></div></div></section>
 <section className="section light"><div className="shell"><div className="catalogue-head"><div><p className="eyebrow dark">Quartz brands</p><h2>One catalogue.<br/><em>Better comparisons.</em></h2></div><p className="section-intro">StoneMatch is not tied to a single quartz brand. That means we can start with the design you love, then compare suitable routes through our supplier and fabrication network.</p></div><div className="catalogue-grid">{quartzBrands.map((brand,i)=><a className={i===0?"catalogue-card featured":"catalogue-card"} href={i===0?"/materials/quartz/partner-range":`/materials/quartz/brands/${brand.slug}`} key={brand.slug}><small>{i===0?"STONEMATCH CURATED":"QUARTZ BRAND"}</small><h3>{brand.name}</h3><p>{brand.strapline}</p><span>{i===0?"Explore 4 collections →":"Explore brand →"}</span></a>)}</div></div></section>
 <section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Already seen a colour?</p><h2>Send us the name.<br/><em>We’ll do the comparison.</em></h2></div><div className="reason-copy dark-copy"><p>If you have already found a quartz you like — from a kitchen retailer, showroom, Instagram or a manufacturer — tell us the brand and colour. StoneMatch can use that as the benchmark rather than making you start again.</p><a className="button gold" href="/?material=Quartz#enquire">Match my quartz →</a></div></div></section>
 </Page>}
