import { Page } from "../components/site-shell";
import { getQuartzBrand } from "../data/quartz-brands";

export function meta({params}:any){const brand=getQuartzBrand(params.slug);return [{title:`${brand?.name||"Quartz Brand"} Worktops | StoneMatch`},{name:"description",content:brand?`Explore ${brand.name} quartz with StoneMatch and compare suitable surfaces, specification, fabrication and installed value.`:"Explore quartz brands with StoneMatch."}]}

export default function QuartzBrand({params}:any){const brand=getQuartzBrand(params.slug);if(!brand)return <Page><section className="page-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Quartz</p><h1>Brand not found.</h1><a className="button gold" href="/materials/quartz">Back to quartz →</a></div></section></Page>;
 return <Page>
  <section className="page-hero brand-hero"><div className="shell narrow"><p className="eyebrow">Quartz · StoneMatch Brand Catalogue</p><h1>{brand.name}</h1><p className="lead">{brand.strapline}</p><div className="hero-actions"><a className="button gold" href={`/?material=Quartz&colour=${encodeURIComponent(brand.name)}#enquire`}>Ask StoneMatch about {brand.name} →</a><a className="text-link light-link" href="/materials/quartz">Compare quartz brands →</a></div></div></section>
  <section className="section light"><div className="shell brand-detail"><div><p className="eyebrow dark">StoneMatch view</p><h2>Choose the surface.<br/><em>Compare the whole job.</em></h2><p className="brand-summary">{brand.summary}</p>{brand.note&&<p className="brand-note">{brand.note}</p>}</div><aside className="brand-facts"><div><small>BEST FOR</small>{brand.bestFor.map(item=><span key={item}>✓ {item}</span>)}</div><dl><div><dt>Material</dt><dd>Quartz</dd></div><div><dt>Finishes</dt><dd>{brand.finishes}</dd></div><div><dt>Thickness</dt><dd>{brand.thicknesses}</dd></div></dl>{brand.website&&<a className="text-link" href={brand.website} target="_blank" rel="noreferrer">Visit manufacturer website ↗</a>}</aside></div></section>
  <section className="section dark-section"><div className="shell split"><div><p className="eyebrow">The StoneMatch difference</p><h2>Found a colour you love?<br/><em>That’s the starting point.</em></h2></div><div className="reason-copy"><p>Send StoneMatch the exact colour or inspiration. We can then compare availability, thickness, finish, fabrication details and the installed quotation through the right partner.</p><p><strong>You do not have to know which supplier or fabricator to call.</strong></p><a className="button gold" href={`/?material=Quartz&colour=${encodeURIComponent(brand.name)}#enquire`}>Start my match →</a></div></div></section>
 </Page>;
}
