import { Page } from "../components/site-shell";
import { quartzBrands } from "../data/quartz-brands";

const seoSchema={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","name":"Quartz Worktops","url":"https://stonematch.co.uk/materials/quartz/","description":"Engineered Quartz kitchen worktops, brands, specifications and buying guidance from StoneMatch.","publisher":{"@id":"https://stonematch.co.uk/#organization"}},{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://stonematch.co.uk/"},{"@type":"ListItem","position":2,"name":"Materials","item":"https://stonematch.co.uk/materials/"},{"@type":"ListItem","position":3,"name":"Quartz Worktops","item":"https://stonematch.co.uk/materials/quartz/"}]}]};
export function meta(){return [{tagName:"link",rel:"canonical",href:"https://stonematch.co.uk/materials/quartz/"},{title:"Quartz Worktops & Brands | StoneMatch"},{name:"description",content:"Explore quartz worktops and leading brands, then let StoneMatch compare suitable supply, fabrication and installation routes to find better value."}]}

export default function QuartzCatalogue(){return <Page><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(seoSchema)}}/>
 <section className="page-hero quartz-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Quartz Catalogue</p><h1>Find the quartz you love.<br/><em>Then pay the right price.</em></h1><p className="lead">Quartz should not be a choice between hundreds of names on a screen. Start with our curated Partner Range or explore recognised brands, then let StoneMatch compare the surface, specification, fabrication and installed value.</p><div className="hero-actions"><a className="button gold" href="/materials/quartz/partner-range/">Explore Partner Range →</a><a className="text-link light-link" href="/worktop-matcher/">Not sure? Use the Worktop Matcher →</a></div></div></section>
 <section className="section light"><div className="shell"><div className="catalogue-head"><div><p className="eyebrow dark">Quartz brands</p><h2>One catalogue.<br/><em>Better comparisons.</em></h2></div><p className="section-intro">StoneMatch is not tied to a single quartz brand. That means we can start with the design you love, then compare suitable routes through our supplier and fabrication network.</p></div><div className="catalogue-grid">{quartzBrands.map((brand,i)=><a className={i===0?"catalogue-card featured":"catalogue-card"} href={i===0?"/materials/quartz/partner-range":`/materials/quartz/brands/${brand.slug}`} key={brand.slug}><small>{i===0?"STONEMATCH CURATED":"QUARTZ BRAND"}</small><h3>{brand.name}</h3><p>{brand.strapline}</p><span>{i===0?"Explore 4 collections →":"Explore brand →"}</span></a>)}</div></div></section>
 <section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Already seen a colour?</p><h2>Send us the name.<br/><em>We’ll do the comparison.</em></h2></div><div className="reason-copy dark-copy"><p>If you have already found a quartz you like — from a kitchen retailer, showroom, Instagram or a manufacturer — tell us the brand and colour. StoneMatch can use that as the benchmark and look for a better-value installed route.</p><a className="button gold" href="/?material=Quartz#enquire">Find my quartz for less →</a></div></div></section><section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">StoneMatch guides</p><h2>Understand the material.<br/><em>Then compare the job.</em></h2></div><div className="reason-copy dark-copy"><p><a className="text-link" href="/guides/how-much-do-quartz-worktops-cost/">How much do Quartz worktops cost? →</a></p><p><a className="text-link" href="/guides/20mm-vs-30mm-quartz-worktops/">20mm vs 30mm Quartz →</a></p><p><a className="text-link" href="/guides/quartz-vs-porcelain-worktops/">Quartz vs Porcelain →</a></p></div></div></section>
<section className="section light"><div className="shell narrow"><h2>Quartz cleaning and care</h2><p><a className="text-link" href="/guides/quartz-worktop-care/">Read the StoneMatch guide →</a></p></div></section></Page>}
