import { Page } from "../components/site-shell";

export function meta(){return [{title:"Why StoneMatch? | Smarter Worktop Buying"},{name:"description",content:"Why StoneMatch exists: experienced stone industry guidance to help homeowners choose the right worktop, compare like-for-like and avoid overpaying."}]}

export default function WhyStoneMatch(){return <Page>
<section className="page-hero"><div className="shell narrow"><p className="eyebrow">Why StoneMatch?</p><h1>The right worktop.<br/><em>The right decision.</em></h1><p className="lead">We use real stone-industry knowledge to help you understand what you're buying, choose with confidence and avoid paying more than you need to.</p></div></section>

<section className="section light"><div className="shell split"><div><p className="eyebrow dark">Why we do it</p><h2>Buying worktops should be exciting.<br/><em>Not confusing.</em></h2></div><div className="reason-copy dark-copy"><p>For most homeowners, a stone worktop is a significant purchase. Yet quotations can be difficult to compare and the cheapest headline price is not always the best deal.</p><p>Different materials, thicknesses, edge details, cut-outs, fabrication, templating and installation can all change what you're actually getting for your money.</p><p><strong>StoneMatch exists to give you clarity before you commit.</strong> We help you understand the complete proposition so you can make the right choice without overpaying.</p></div></div></section>

<section className="section dark-section"><div className="shell split"><div><p className="eyebrow">Knowledge that matters</p><h2>Industry experience.<br/><em>Working for you.</em></h2></div><div className="reason-copy"><p>Our experience comes from working within the stone and worktop industry — dealing with materials, quotations, suppliers, fabricators, kitchen companies and customers.</p><p>That means we understand what sits behind a quotation: where genuine value can be created, which specification details matter, where costs can increase unnecessarily and what questions should be asked before an order is placed.</p><p><strong>We don't just compare two totals. We compare what you are actually being offered.</strong></p></div></div></section>

<section className="section light"><div className="shell"><p className="eyebrow dark">What StoneMatch looks at</p><h2>More than <em>just the price.</em></h2><div className="steps"><article className="step"><span>01</span><h3>Material</h3><p>Is it the right stone for your design, lifestyle, performance needs and budget?</p></article><article className="step"><span>02</span><h3>Specification</h3><p>We consider thickness, edges, cut-outs, upstands, splashbacks and other details that affect the finished job.</p></article><article className="step"><span>03</span><h3>Fabrication & installation</h3><p>Who is measuring, manufacturing and fitting the worktops — and what level of service is included?</p></article><article className="step"><span>04</span><h3>Value</h3><p>We compare the complete package like-for-like to help establish whether the price makes sense.</p></article></div></div></section>

<section className="section cream-band"><div className="shell split"><div><p className="eyebrow dark">Our approach</p><h2>A good deal is still<br/><em>a good deal.</em></h2></div><div className="reason-copy dark-copy"><p>StoneMatch isn't here to tell you that every quotation is too expensive. If your existing quote offers the right material, specification, service and price, we'll tell you.</p><p>If we believe there's a better-value or more suitable route, we'll explain why. The final choice remains yours.</p><p><strong>Our purpose is simple: help you spend your money wisely and feel confident about the worktops you choose.</strong></p><a className="button gold" href="/#enquire">StoneMatch my quote</a></div></div></section>
</Page>}
