import { useMemo,useState } from "react";
import { Page } from "../components/site-shell";
type M="Quartz"|"Porcelain"|"Granite"|"Marble"; const mats:M[]=["Quartz","Porcelain","Granite","Marble"];
const qs=[
 ["What matters most to you in a worktop?",[["Easy maintenance",{Quartz:3,Porcelain:3}], ["Excellent heat resistance",{Porcelain:4,Granite:4,Marble:2}], ["Natural beauty",{Marble:4,Granite:4}], ["A statement design",{Marble:4,Porcelain:3,Granite:2}]]],
 ["How busy is your kitchen?",[["Light use",{Marble:2,Quartz:1}], ["Normal family use",{Quartz:3,Porcelain:3,Granite:2}], ["Very busy",{Porcelain:4,Granite:3,Quartz:3}], ["Commercial-style cooking at home",{Porcelain:4,Granite:4,Quartz:-2}]]],
 ["How important is stain resistance?",[["Essential",{Porcelain:4,Quartz:3}], ["Important",{Quartz:3,Porcelain:3,Granite:2}], ["Not a major concern",{Marble:3,Granite:2}]]],
 ["Do you regularly put hot pans or trays near your worktop?",[["Yes, frequently",{Porcelain:5,Granite:5,Marble:2,Quartz:-3}], ["Occasionally",{Porcelain:3,Granite:3,Quartz:1}], ["Rarely or never",{Quartz:3,Marble:2}]]],
 ["How do you feel about natural variation?",[["I prefer a consistent appearance",{Quartz:4,Porcelain:3}], ["Some variation is fine",{Granite:3,Quartz:2,Porcelain:2}], ["I love every slab being unique",{Marble:5,Granite:5}]]],
 ["How much maintenance are you comfortable with?",[["As little as possible",{Porcelain:5,Quartz:4,Marble:-2}], ["Occasional care is fine",{Granite:4,Quartz:2,Porcelain:2}], ["Happy to care for it for the right look",{Marble:5,Granite:3}]]],
 ["Which look are you most drawn to?",[["Clean and contemporary",{Quartz:4,Porcelain:4}], ["Elegant marble-inspired veining",{Porcelain:4,Quartz:4,Marble:3}], ["Natural and characterful",{Granite:5,Marble:4}], ["Dramatic statement stone",{Marble:5,Granite:4,Porcelain:3}]]],
 ["Where will the surface be used?",[["Kitchen",{Quartz:2,Porcelain:2,Granite:2,Marble:1}], ["Utility room",{Quartz:3,Porcelain:3,Granite:2}], ["Bathroom",{Porcelain:4,Quartz:3,Marble:2}], ["Outdoor kitchen or BBQ area",{Porcelain:7,Granite:7,Quartz:-8}]]],
 ["What is most important in your final decision?",[["Everyday practicality",{Quartz:4,Porcelain:4,Granite:2}], ["Appearance and luxury",{Marble:5,Porcelain:3,Granite:3,Quartz:2}], ["Longevity and toughness",{Granite:5,Porcelain:5,Quartz:2}], ["A balance of everything",{Quartz:4,Porcelain:4,Granite:3,Marble:1}]]]
] as const;
const info:Record<M,{intro:string;reasons:string[]}>= {Quartz:{intro:"Quartz is a strong match for the way you want to use and enjoy your space, combining huge design choice with straightforward everyday care.",reasons:["Low-maintenance everyday surface","Huge choice of colours and patterns","Consistent, controlled appearance","Excellent for many family kitchens"]},Porcelain:{intro:"Porcelain looks like the strongest match for your project, especially where heat resistance, low maintenance and striking design matter.",reasons:["Excellent heat resistance","Highly resistant to staining","Very low maintenance","Wide choice of stone-inspired designs"]},Granite:{intro:"Granite looks like an excellent fit if you value genuine natural stone, individual character and a surface capable of working hard.",reasons:["Genuine natural stone","Every slab is individual","Excellent heat resistance","Strong, long-lasting option"]},Marble:{intro:"Marble looks like your natural match: authentic beauty and individuality, with the care a luxury natural surface deserves.",reasons:["Authentic natural veining","Every slab is unique","Timeless premium appearance","Exceptional statement material"]}};
const exploreHref:Record<M,string>={Quartz:"/materials/quartz/partner-range",Porcelain:"/materials/porcelain/partner-range",Granite:"/materials",Marble:"/materials"};
export function meta(){return [{title:"Worktop Matcher | Find Your Perfect Worktop | StoneMatch"},{name:"description",content:"Answer 9 quick questions and StoneMatch will recommend whether quartz, porcelain, granite or marble best suits your project."}]}
export default function Matcher(){const [step,setStep]=useState(0),[answers,setAnswers]=useState<number[]>([]),[done,setDone]=useState(false); const result=useMemo(()=>{const s:Record<M,number>={Quartz:0,Porcelain:0,Granite:0,Marble:0};answers.forEach((a,i)=>{const w=qs[i]?.[1]?.[a]?.[1] as Partial<Record<M,number>>|undefined;if(w)mats.forEach(m=>s[m]+=w[m]||0)});return mats.slice().sort((a,b)=>s[b]-s[a])},[answers]); function choose(i:number){const n=[...answers];n[step]=i;setAnswers(n);if(step===qs.length-1)setDone(true);else setStep(step+1)} function reset(){setStep(0);setAnswers([]);setDone(false)} const pct=Math.round(((done?qs.length:step+1)/qs.length)*100); const quoteHref=`/?material=${encodeURIComponent(result[0])}&matcher=${encodeURIComponent(result[0])}&source=matcher#enquire`;return <Page><section className="page-hero matcher-hero"><div className="shell narrow"><p className="eyebrow">StoneMatch Worktop Matcher</p><h1>What worktop<br/><em>suits you best?</em></h1><p className="lead">Nine quick questions. No jargon. We’ll narrow down Quartz, Porcelain, Granite and Marble based on how you actually want to live with your worktop.</p></div></section><section className="section cream-band"><div className="shell"><div className="matcher-box"><div className="matcher-progress"><span>{done?"Your result":`Question ${step+1} of ${qs.length}`}</span><i><b style={{width:`${pct}%`}}/></i><strong>{pct}%</strong></div>{!done?<div className="matcher-question"><p className="eyebrow dark">Find your perfect surface</p><h2>{qs[step][0]}</h2><div className="matcher-options">{qs[step][1].map((o,i)=><button key={o[0]} onClick={()=>choose(i)}>{o[0]}<span>→</span></button>)}</div><div className="matcher-nav"><button disabled={step===0} onClick={()=>setStep(Math.max(0,step-1))}>← Back</button><button onClick={reset}>Start again</button></div></div>:<div className="matcher-result"><p className="eyebrow dark">Your StoneMatch</p><h2>{result[0]}</h2><p className="result-lead">{info[result[0]].intro}</p><div className="result-reasons">{info[result[0]].reasons.map(x=><span key={x}>✓ {x}</span>)}</div><div className="also"><small>ALSO WORTH CONSIDERING</small><strong>{result[1]}</strong><p>{result[1]} also scored highly. We can compare both against your design, colour choice and budget.</p></div><div className="result-actions"><a className="button gold" href={exploreHref[result[0]]}>Explore my {result[0]} options →</a><a className="button outline" href={quoteHref}>Get a quote for my match →</a></div><p className="matcher-result-note">Your {result[0]} result will be carried into the quote form automatically.</p><button className="retake" onClick={reset}>Retake the matcher</button></div>}</div></div></section></Page>}
